### PR TITLE
Updated helps with on-premises SVN related details

### PR DESCRIPTION
**Pull request by tuhinmitra888**

### CODE REVIEW

**Comment by joerih** [comment]
Please don't merge this yet; we still need to make a few more changes.

**Comment by jandevriesmendix** [comment]
@joerih Please investigate the conflicts. Are you working on the latest version of these docs?

**Comment by JelteMX** [comment]
@jandevriesmendix Checked the [development branch](https://github.com/tuhinmitra888/docs/commits/development) for this PR. Forked around July 11, approx 600 commits behind. @tuhinmitra888 you should first merge our development branch into yours to get the latest updates

**Comment by tuhinmitra888** [comment]
Closing, as there is an updated one - https://github.com/mendix/docs/pull/767

**Pull request closed without merging**
