### PR TITLE
Update _index.md

### PR DESCRIPTION
**Pull request by udh-mendix**
Add release notes for update in alerting template

### CODE REVIEW

**Comment by Adam-Dupaski** [comment]
@MarkvanMents I think this should be in some Deployment RN?

**Comment by MarkvanMents** [comment]
@udh-mendix 
Where do these alerts come from. Mendix Cloud?
I think they would be better in https://docs.mendix.com/releasenotes/developer-portal/mendix-cloud/?

**Comment by udh-mendix** [comment]
@MarkvanMents you're right, I'll move them to the correct place. Closing this PR.

**Comment by MarkvanMents** [comment]
Thanks Umang.

**Pull request closed without merging**
