### PR TITLE
make the list of Data Set parameter types up to date

### PR DESCRIPTION
**Pull request by basi01**
No String for you peasants!

### CODE REVIEW

**Review by MarkvanMents — APPROVED** [review]
Hi Ilya (@basi01)
Thanks for correcting this error in our documentation. I've confirmed that there is an error here and have approved your PR.
Can I ask you just to sign our license/cla 👇 just to confirm that we can use your change. I know it seems excessive for such a minor addition, but it keeps our PRs clean and avoids questions later.
Great that you took the trouble to make this change for us, makes the documentation better for everyone. Please continue to let us know of any other errors you spot.
Yours
Mark

**Comment by basi01** [comment]
@MarkvanMents it says
> Hey, basi01!
> You have agreed to the CLA for mendix/docs

Alternatively, it shows the agreement text, but all the form inputs are greyed

**Comment by MarkvanMents** [comment]
Thanks @basi01 
Sigh! This keeps happening for people's first submission to our repo. I'll do some more investigation. Sometimes happens when people have multiple GitHub accounts, but that doesn't seem to be the case.

Anyhow - sorry for the inconvenience. Thanks for getting back so promptly. I'll merge this now.
Mark

**Comment by MarkvanMents** [comment]
Hi @basi01
> Sometimes happens when people have multiple GitHub accounts, but that doesn't seem to be the case.

or perhaps this is the case, as I see that @basinilya is also listed on this PR. The commit was made by @basinilya but the PR was made by @basi01 - so the CLA is right that the account that made the commit hasn't signed the CLA!
 
image

Anyhow - sorted out and merged now. Thanks again for your submission.

**Pull request merged**
