### PR TITLE
Documented service name, custom location and version feature in published REST service.

### PR DESCRIPTION
**Pull request by grbinho**
In 7.11 we will be releasing an new feature for Published REST service.

Users will now be able to choose custom paths when creating Published REST service.
Here is the reference documentation.

### CODE REVIEW

**Comment by grbinho** [comment]
@Adam-Dupaski Hi Adam. This feature will not make it for 7.11. I have update the text to 7.12.

**Comment by grbinho** [comment]
@Adam-Dupaski 
Hi Adam, I added additional documentation in this PR. We have a couple of changes for this page and I think it's easier to review in single PR.

**Comment by Adam-Dupaski** [comment]
@grbinho Hi Ivan, there are conflicts now with this PR, as #939 has already been merged. Is the currently published doc correct?
https://docs.mendix.com/refguide/published-rest-service
Or does this PR also have to be merged? We need to work together to finish this pull request. Another option is to close this PR and open a new PR on the doc to make any more necessary changes. Please let me know. Thanks.

**Comment by grbinho** [comment]
@Adam-Dupaski I fixed up this PR. should be good now.

**Pull request merged**
