### PR TITLE
Remove story-template functionality

### PR DESCRIPTION
**Pull request by loket4**

### CODE REVIEW

**Comment by Adam-Dupaski** [comment]
@loket4 do you work for Mendix? I don't see a recognizable name or Mendix identified on your profile. If you do, this would be better as a release note, along with a doc update. When was this released?

**Comment by Adam-Dupaski** [comment]
https://github.com/loket4/docs/pull/1
https://github.com/loket4/docs/pull/2

**Comment by Adam-Dupaski** [comment]
@loket4 I removed that section after verifying in Dev Portal. Question remains for release note - see linked PRs above.

**Comment by Adam-Dupaski** [comment]
Updated RN manually due to lack of communication

**Comment by loket4** [comment]
Hi Adam, Indeed I wok for Mendix. I updated my profile as such.
We plan a new release of Sprintr tomorrow (Wednesday). Because we have one more item to test, the release notes are not yet final.
Kin regards, Olaf Joppe.

**Pull request closed without merging**
