### PR TITLE
Add new documentation for runtime request handlers

### PR DESCRIPTION
**Pull request by Robinfr**
Added new documentation to describe the various runtime request handlers that the client uses. More request handlers can be added in the future by other teams.

### CODE REVIEW

**Comment by Robinfr** [comment]
@MarkvanMents I think this can be reviewed by you :)

**Comment by MarkvanMents** [comment]
> @MarkvanMents I think this can be reviewed by you :)

@Robinfr - I've found some more places to link to this document, and done a proofread.
See https://github.com/mendix/docs/pull/7979/commits/a155dbe5bf4955fa78bf7a5cba3a91be87dd1a13
Can you have a look and let me know if my updates make sense. Thanks.

**Comment by MarkvanMents** [comment]
@Robinfr 
Do you have any feedback on my changes, or is it OK to publish this?

**Comment by Robinfr** [comment]
@MarkvanMents Apologies! I missed this somehow. I took a look at your changes, and they all look good 👍 It can be published 😄 Thanks for taking the time to review

**Comment by MarkvanMents** [comment]
Thanks for the confirmation Robin. Merging now.

**Review by MarkvanMents — APPROVED** [review]

**Pull request merged**
