### PR TITLE
CAT-1872-release-notes-for-catalog-1.47

### PR DESCRIPTION
**Pull request by ysmendix**
This PR contains release notes for Catalog version 1.47

### CODE REVIEW

**Comment by MarkvanMents** [comment]
Can you tell me the release date for this?
Thanks.

**Comment by ysmendix** [comment]
Release date 16th September 2021

**Review by MarkvanMents — APPROVED** [review]

**Comment by MarkvanMents** [comment]
> 
> 
> Release date 16th September 2021

Thanks - can you let us know here, or via Slack when I can publish the release notes?

**Comment by ysmendix** [comment]
Data Hub release is planned between 8:00 - 09:00.

**Comment by MarkvanMents** [comment]
Can you confirm here that it was successful and I'll publish. I'll be in the office around 9:00
Thanks for the Pull Request.
(Should have spotted it was for 16th - somehow I missed the important line highlighting the date!)

**Comment by MarkvanMents** [comment]
Hi Yash,
@ysmendix can you confirm the release was successful and I'll publish the documentation.
Thanks.

**Pull request merged**
