### PR TITLE
Update tencent-deploy.md

### PR DESCRIPTION
**Pull request by Luyao-Zhang-1**

### CODE REVIEW

**Comment by Luyao-Zhang-1** [comment]
@MarkvanMents could you please take a look at this PR?

**Review by MarkvanMents — APPROVED** [review]
Great changes 
A bit embarrassing how many there are, but it's great that you've caught them.
I'd be interested in your thoughts on the structure. Some of these documents are more technical than the general documentation (or at least, have more steps needed to complete the task) and it is difficult to see them with a fresh eye. I hope it was OK to follow what was going on.

Feel free to merge these changes if you have the rights.
Thanks for the review.
Mark

**Comment by Luyao-Zhang-1** [comment]
> Great changes
> A bit embarrassing how many there are, but it's great that you've caught them.
> I'd be interested in your thoughts on the structure. Some of these documents are more technical than the general documentation (or at least, have more steps needed to complete the task) and it is difficult to see them with a fresh eye. I hope it was OK to follow what was going on.
> 
> Feel free to merge these changes if you have the rights.
> Thanks for the review.
> Mark

Hi @MarkvanMents, no problem. It happens to the best of us. Sorry, I did not have time to comprehend the real content of the doc. I focused more on whether the translation is complete, consistent, and not ambiguous. So I cannot give much feedback on the structure of this doc. There is only one thing I would probably do differently, which is not about structure of this doc: sometimes, in a numbered list, a description is listed as a separate list item (for example, step 2 in the procedure in 4.1). I would prefer to only make an action from the user side a list item. Other types of information, such as results of actions descriptions would be added to the most relevant step. What do you think?

**Comment by MarkvanMents** [comment]
> 
> 
> > Great changes
> > A bit embarrassing how many there are, but it's great that you've caught them.
> > I'd be interested in your thoughts on the structure. Some of these documents are more technical than the general documentation (or at least, have more steps needed to complete the task) and it is difficult to see them with a fresh eye. I hope it was OK to follow what was going on.
> > Feel free to merge these changes if you have the rights.
> > Thanks for the review.
> > Mark
> 
> Hi @MarkvanMents, no problem. It happens to the best of us. Sorry, I did not have time to comprehend the real content of the doc. I focused more on if the translation is complete, consistent, and not ambiguous. So I cannot give much feedback on the structure of this doc. There is only one thing I would probably do differently, which is not about structure of this doc: sometimes, in a numbered list, a description is listed as a separate list item (for example, step 2 in the procedure in 4.1). I would prefer to only make an action from the user side a list item. Other types of information, such as results of actions would be added to the most relevant step. What do you think?

Yes, definitely. I agree that is best practice and I do try to follow that. I obviously missed it this time.
Thanks for picking it up.

**Pull request merged**
