### PR TITLE
Added best practices category for ATS

### PR DESCRIPTION
**Pull request by GeorgHolz**

### CODE REVIEW

**Comment by Adam-Dupaski** [comment]
George, please take a minute to sign the [CLA](https://www.clahub.com/agreements/mendix/docs).
Thanks.

**Comment by Adam-Dupaski** [comment]
Hi Georg, the review is finished. This will be merged after you have signed the [CLA](https://www.clahub.com/agreements/mendix/docs).
Thanks.

**Comment by Adam-Dupaski** [comment]
Upon merge, add include block.

**Comment by Adam-Dupaski** [comment]
Removed this section from beginning of doc, because these docs do not exist yet and this was breaking the build:

In addition, take a look at the how-to's for building a custom action:

* [How to Create a Combined Action](../refguide-ats-1/create-a-combined-action)
* [How to Create a Search Context Action](../howtos/create-search-context-action)
* [How to Create an Unsupported Widget Action](../refguide-ats-1/create-unsupported-widget-action)
* [How to Create a Function Action](../howtos/create-function-action)

Georg, in future PRs, please do not include links to docs that do not exist yet.

**Comment by GeorgHolz** [comment]
I’ve forwarded this info to the author.
Is there already a way how we can check links ourself?

Von: Adam Dupaski [mailto:notifications@github.com]
Gesendet: Donnerstag, 22. Juni 2017 10:26
An: mendix/docs <docs@noreply.github.com>
Cc: Georg Holz <georg.holz@mansystems.de>; Author <author@noreply.github.com>
Betreff: Re: [mendix/docs] Added best practices category for ATS (#499)


Removed this section from beginning of doc, because these docs do not exist yet and this was breaking the build:

In addition, take a look at the how-to's for building a custom action:

  *   How to Create a Combined Action<../refguide-ats-1/create-a-combined-action>
  *   How to Create a Search Context Action<../howtos/create-search-context-action>
  *   How to Create an Unsupported Widget Action<../refguide-ats-1/create-unsupported-widget-action>
  *   How to Create a Function Action<../howtos/create-function-action>

Georg, in future PRs, please do not include links to docs that do not exist yet.

**Comment by Adam-Dupaski** [comment]
That seems like a matter of internal coordination for the authors of these docs.

**Pull request merged**
