### PR TITLE
[8.13] Paging bar options

### PR DESCRIPTION
**Pull request by r0b1n**

### CODE REVIEW

**Comment by Adam-Dupaski** [comment]
@MariaShaposhnikova please verify the change to the Studio screenshot here, and see if there are any changes to Studio docs necessary.

**Comment by MariaShaposhnikova** [comment]
@Adam-Dupaski , thanks for tagging me!
@r0b1n , will Show Paging Controls and/or Show Buttons be replaced in Studio as well?

**Comment by MariaShaposhnikova** [comment]
@Adam-Dupaski , I have verified Studio changes with Roman, the PR can be merged when the corresponding version is released.

**Comment by Adam-Dupaski** [comment]
@MariaShaposhnikova please add a border to the Studio screenshot before or after we merge.

**Pull request merged**
