### PR TITLE
Add docs for column tooltip property for Data Grid 2 widget

### PR DESCRIPTION
**Pull request by iobuhov**
Add changes requested in [WC-932](https://mendix.atlassian.net/jira/software/c/projects/WC/boards/418?modal=detail&selectedIssue=WC-932)

### CODE REVIEW

**Review by Keraito — APPROVED** [review]
From technical perspective, everything looks fine. @Luyao-Zhang-1 @ConnorLand do we need to update the previous screenshots as more widget properties have been added since then? It's not really the focus of those screenshots but I can imagine it being confusing, so let us know if we should. (Like the wrap text screenshot which doesn't have the tooltip widget prop but the focus is on "wrap text")

**Comment by ConnorLand** [comment]
> From technical perspective, everything looks fine. @Luyao-Zhang-1 @ConnorLand do we need to update the previous screenshots as more widget properties have been added since then? It's not really the focus of those screenshots but I can imagine it being confusing, so let us know if we should. (Like the wrap text screenshot which doesn't have the tooltip widget prop but the focus is on "wrap text")

Screenshot updates would be most appreciated. After they are committed, please let me know and I will merge.

**Comment by ConnorLand** [comment]
> [CLA assistant check](https://cla-assistant.io/mendix/docs?pullRequest=3999) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/mendix/docs?pullRequest=3999) before we can accept your contribution.**1** out of **2** committers have signed the CLA.✅ ConnorLand❌ iobuhovYou have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mendix/docs?pullRequest=3999) it.

Also @iobuhov please complete the CLA agreement mentioned on this page.

**Comment by diego-antonelli** [comment]
@ConnorLand screenshots were updated.

**Comment by ConnorLand** [comment]
> @ConnorLand screenshots were updated.

Thanks, doing final check now.

**Review by ConnorLand — APPROVED** [review]

**Pull request merged**
