### PR TITLE
Add general section

### PR DESCRIPTION
**Pull request by zwartd**
Accidentally added a broken link in custom-action-prerequisites.md in chapter 8. It refers to basics that i will publish next.

### CODE REVIEW

**Comment by Adam-Dupaski** [comment]
Hi, how do these new docs relate to the "How to Create Custom Action" that is already published? 

https://docs.mendix.com/ats/howtos/create-custom-action

Does this doc need to be moved somewhere?

**Comment by zwartd** [comment]
I am planning on renaming the "How to Create Custom Action" that is already published and move it into another section that i will publish soon. I understand the naming is confusing, could you put it in the background for now?

**Comment by Adam-Dupaski** [comment]
I will merge these PRs and then possibly remove "How to Create Custom Action" after I get a better idea of how the new doc structure looks.

**Comment by zwartd** [comment]
Yes that is fine. FYI, The main document is "Create Custom Actions" which will eventually contain 6 sub documents.
1.	General
Contains basic information for all how-to’s:
	1.	Definitions
	Explains the four different types (Unsupported, Search Context, Combined and Function)
	2.	How-to Prerequisites
	Explains the prerequisites for all the how-to’s. (easier to maintain)
	3.	How-to Structure
	Explains the approach of all how-to’s and it’s relation to the app.
	4.	Helpful resources
	All kinds of helpful tools and sources of information.
	5.	Custom Action App
	Explains the app where you can find the situations of each how-to.

2.	Custom Action Basics
Explains how to create the actions, add parameters etc. (Easier to maintain if one location)

3.	Create Combined Actions
All how-to’s for creating combined actions.

4.	Create Unsupported Widget actions
All how-to’s for creating Unsupported Widget actions. (All events, click, input, with mx-name, without mx-name).

5.	Search Context actions
All how-to’s for creating search context actions.

6.	Create Function actions
All how-to’s for creating search context actions.

I still need to look where the "Create Custom Action" document can fit in, the one that was already present.

**Pull request merged**
