### PR TITLE
Describe database-specific limitations on unlimited string uniqueness

### PR DESCRIPTION
**Pull request by dahfjkg**
Was not sure whether to describe the limitation here or in `case-sensitive-database-behavior`

### CODE REVIEW

**Comment by MarkvanMents** [comment]
Hi Pavel (@dahfjkg),
I think it would be better in this area of the documentation: https://docs.mendix.com/refguide/data-storage/. There is already a link to https://docs.mendix.com/refguide/case-sensitive-database-behavior/, so I think it would be better to have this information there. But then, I think we need to rename the document to something like **Database String Behavior**.

What do you think?
@katarzyna-koltun-mx : do you have any thoughts on this?

In the Oracle documentation, we also mention uniqueness: https://docs.mendix.com/refguide/oracle/#34-uniqueness-constraint - but this seems to be a stricter limitation than the one we are talking about here, so I think it needs to stay specific to the Oracle description.

**Comment by katarzyna-koltun-mx** [comment]
@MarkvanMents That makes sense, but also, we have individual articles on different database types (e.g. https://docs.mendix.com/refguide/mysql/) - maybe this info should be distributed across these articles? I'm thinking a user would typically only need to see the behaviour for their own database type.

But then also the other contents of the article you linked would need to be moved to database-specific articles, so I'm not sure there. If we want to keep it all on one page then the article you linked looks great.

**Comment by dahfjkg** [comment]
@MarkvanMents @katarzyna-koltun-mx I agree. There are more database-specific differences in unlimited string behavior that ability to create a uniqueness constraint. I will create a separate page in data storage and call it `Unlimited String Behavior`

**Comment by dahfjkg** [comment]
@MarkvanMents @katarzyna-koltun-mx I've updated the PR and created a separate page with unlimited string behavior per database. Please check the format of the page

**Comment by katarzyna-koltun-mx** [comment]
@dahfjkg Hi Pavel, I've merged your requested change. It should be published tomorrow.

**Pull request merged**
