### PR TITLE
MxBuild Updates

### PR DESCRIPTION
**Pull request by MarkvanMents**
Updated MxBuild document

I have updated the MxBuild document from experience and added some tips from Arjan v. IJ.

The system requirements are in the system-requirements document, so they are in one place.

### CODE REVIEW

**Comment by MarkvanMents** [comment]
There is one issue with the --loose-version-check option. Can you look and see if there is anything we can help with in terms of documentation.

I can run MxBuild on this 7.13 app and it is OK. However if I run 7.18 MxBuild using --loose-version-check I get the following output including `is not compatible with Mendix 7`. My app is already Mendix 7! 

```
   __  __      ____        _ _     _ 
  |  \/  |    |  _ \      (_) |   | |
  | \  / |_  _| |_) |_   _ _| | __| |
  | |\/| \ \/ /  _ <| | | | | |/ _` |
  | |  | |>  <| |_) | |_| | | | (_| |
  |_|  |_/_/\_\____/ \__,_|_|_|\__,_|

   v7.18.1.40272

Starting build for Mendix Project file: C:\Users\mnt\Dropbox (Mendix)\_LocalFolders\Documents\Mendix\Where is my Meeting Room-main\Where is my Meeting Room.mpr
Using the following options:
 * Build target: Package
Reading project file...
Building project...
Executing step 'Synchronize with file system'
 * Synchronizing with file system...
Executing step 'Initialize'
 * Preparing deployment...
Executing step 'Check prerequisites'
 * Checking for errors...
ERROR: The project cannot be deployed, because it contains errors.
ERROR at Atlas_UI_Resources, Layout 'Phone_Default', Custom widget 'mobileFeatures1': Version '1.2.0' of the 'Mobile Features' widget is not compatible with Mendix 7. Visit the App Store to check for updates.
ERROR at Atlas_UI_Resources, Layout 'Phone_Sidebar', Custom widget 'mobileFeatures1': Version '1.2.0' of the 'Mobile Features' widget is not compatible with Mendix 7. Visit the App Store to check for updates.
BUILD FAILED
```

**Comment by ironthorn** [comment]
> There is one issue with the --loose-version-check option. Can you look and see if there is anything we can help with in terms of documentation.

The error is about a _custom widget_ not being compatible with Mendix 7. So, you need a newer version of the custom widget that is compatible with the Mendix version you are using.

**Comment by ironthorn** [comment]
The MxBuild documentation looks fine. Great that there is a concrete example of the full command-line now!

 I just talked to David and he is probably going to ask you to remove the part about service mode. We usually it internally for the web modeler but we do not see it as an officially supported feature of Mendix.

**Comment by ironthorn** [comment]
> > There is one issue with the --loose-version-check option. Can you look and see if there is anything we can help with in terms of documentation.
> 
> The error is about a _custom widget_ not being compatible with Mendix 7. So, you need a newer version of the custom widget that is compatible with the Mendix version you are using.

The loose version check allows you to open a project that is not exactly the same version as MxBuild itself. For example, with that option you can open a 7.10.0 project with a 7.17.1 MxBuild.

**Comment by MarkvanMents** [comment]
> 
> 
> > > There is one issue with the --loose-version-check option. Can you look and see if there is anything we can help with in terms of documentation.
> > 
> > 
> > The error is about a _custom widget_ not being compatible with Mendix 7. So, you need a newer version of the custom widget that is compatible with the Mendix version you are using.
> 
> The loose version check allows you to open a project that is not exactly the same version as MxBuild itself. For example, with that option you can open a 7.10.0 project with a 7.17.1 MxBuild.

Yes - but I am upgrading from 7.13 to 7.18, so they are both Mendix 7. Therefore the error message is misleading/wrong.

I'll leave it for now - it probably won't hit many people.

**Comment by MarkvanMents** [comment]
> 
> 
> The MxBuild documentation looks fine. Great that there is a concrete example of the full command-line now!
> 
> I just talked to David and he is probably going to ask you to remove the part about service mode. We usually it internally for the web modeler but we do not see it as an officially supported feature of Mendix.

I'll wait to hear from David before releasing.

**Comment by MarkvanMents** [comment]
Removed section on service mode and proofread.

I can merge it to be published as soon as everyone is happy. Please let me know if you have nay more comments.

**Pull request merged**
