### PR TITLE
Customize styling and Atlas UI changes

### PR DESCRIPTION
**Pull request by cjfhodges**
Customize styling changes to create a re-usable theme module

Layout best practices

### CODE REVIEW

**Comment by ConnorLand** [comment]
@cjfhodges do you know what these DS_Store files in your PR are?

**Comment by cjfhodges** [comment]
I don't know. Is it possible to reject them? or should I resubmit the pull request without them?

**Comment by ConnorLand** [comment]
> I don't know. Is it possible to reject them? or should I resubmit the pull request without them?

I deleted them, so no worries there. If you figure out how they got included please let me know. I wonder if it's a Mac thing?

**Comment by ConnorLand** [comment]
This PR solves the following issues:
* Support JIRA issue [TW-1645](https://mendix.atlassian.net/browse/TW-1645)
*  GH Issue #4138

**Review by ConnorLand — APPROVED** [review]

**Pull request merged**
