### PR TITLE
Add task queue helper to queue docs

### PR DESCRIPTION
**Pull request by grootjans**

### CODE REVIEW

**Review by MarkvanMents — APPROVED** [review]
Hi Robbert Jan (@grootjans),
I've proofread this and changed it a bit. Can it be published now?
Mark

**Comment by MarkvanMents** [comment]
@grootjans - is it OK to publish this? I think the module is published in Marketplace?
Thanks

**Comment by MarkvanMents** [comment]
@grootjans @jds-mendix 
Robbert Jan/Jan David
Can either of you confirm that this can be published?
Thanks

**Comment by jds-mendix** [comment]
Yes, please go ahead :)

**Comment by MarkvanMents** [comment]
Now published to production: https://docs.mendix.com/refguide/task-queue#4-other

**Pull request merged**
