### PR TITLE
Corrected DB RAM for 3XL resource pack

### PR DESCRIPTION
**Pull request by Sakshi-Dhakad**

### CODE REVIEW

**Comment by Adam-Dupaski** [comment]
Hi @Sakshi-Dhakad thanks for the PR. Please identify your company as Mendix on your GitHub profile via Mendix protocol so that we know who's sending the doc update. Thanks.

**Comment by katarzyna-koltun-mx** [comment]
@Sakshi-Dhakad Hey Sakshi, I've got a warning from github because your CLA is not signed. Could you sign it? We'd like to process your request asap. Let me know if you need any additional info.

**Comment by Sakshi-Dhakad** [comment]
How do I sign my CLA in Github? Are there any instructions?

Sakshi Dhakad
Mendix | Product Manager | Public Cloud

**Comment by katarzyna-koltun-mx** [comment]
@Sakshi-Dhakad Thank you for your quick response! You can sign the CLA here: https://cla-assistant.io/mendix/docs

Let me know if there are any issues - in either case, I'll merge your change today, but signing the CLA will make sure we don't have any similar errors in the future.

**Comment by Sakshi-Dhakad** [comment]
Thanks, I’ve signed it!

Cheers,

Sakshi Dhakad
Mendix | Product Manager | Public Cloud

**Review by katarzyna-koltun-mx — APPROVED** [review]
Thank you! Approving the merge now.

**Comment by Sakshi-Dhakad** [comment]
@katarzyna-koltun-mx  - Thanks! I do not see the changes live in Production yet. Do you know typically how long it takes? or what the downstream steps in the process are? 
I edited this page - https://docs.mendix.com/developerportal/deploy/mendix-cloud-deploy/

**Comment by katarzyna-koltun-mx** [comment]
@Sakshi-Dhakad We normally publish the changes in batches, usually once per day or so. Your changes should be published to production within that approximate time. If a change is more urgent, I can have it published faster though, so let me know.

**Comment by katarzyna-koltun-mx** [comment]
@Sakshi-Dhakad Your change should now be visible on production.

**Comment by Sakshi-Dhakad** [comment]
Good to know! It’s not urgent, as long as it makes it to production soon, it’s good.

Cheers,

Sakshi Dhakad
Mendix | Product Manager | Public Cloud

**Comment by Sakshi-Dhakad** [comment]
Thanks, added a company name to my profile.

Cheers,

Sakshi Dhakad
Mendix | Product Manager | Public Cloud

**Pull request merged**
