### PR TITLE
[DAT-2081] Make string-functions perform case-insensitively on SapHana

### PR DESCRIPTION
**Pull request by nimatrueway**
RN
Make string-functions perform case-insensitively on SapHana

### CODE REVIEW

**Comment by ishan1729** [comment]
I approve of the changes.

**Comment by MarkvanMents** [comment]
Hi @nimatrueway ,
Looks great. Three questions:
1. When will this be released, or is it the current status?
2. Does this apply to all versions of Mendix or is it version specific?
3. Does the user have to do anything to an existing SAP Hana database to get it to apply?

Thanks

**Comment by nimatrueway** [comment]
Hi @MarkvanMents !

> When will this be released, or is it the current status?
> Does this apply to all versions of Mendix or is it version specific?

The change will be in effect since the next minor release, namely **8.11** (and any release after that ofcourse).

> Does the user have to do anything to an existing SAP Hana database to get it to apply?

They will notice the change right away. No extra configuration is required.

**Comment by MarkvanMents** [comment]
I think that we need to say what the situation was in Mx <8.11 for users who may be using earlier versions of Mendix. I'll add something.

**Comment by MarkvanMents** [comment]
@nimatrueway,
Hi. I've added a quick note to both the documents that if users have a version before 8.11 they will get case sensitive behavior.
Let me know if you have any comments, otherwise I'll assume this PR is ready to go with 8.11.

**Comment by nimatrueway** [comment]
Thank you @MarkvanMents, it became clearer. :+1:

**Pull request merged**
