### PR TITLE
Update sap logging connector doc

### PR DESCRIPTION
**Pull request by cstevandy**
We have a new version of sap logging connector based on input from users. Please find the updated connector here: https://appstore.home-accp.mendix.com/link/app/709/.

Changes:
- Enumeration LogLevels is replaced with constant SapLogLevel.
- Java action RegisterSubscriber LogLevel input parameter is replaced with a String. Constant SapLogLevel can be used as an input.

### CODE REVIEW

**Comment by MarkvanMents** [comment]
@cstevandy - This looks OK - however, I'd rather resize the images than fiddle with the html directly.
I've resized the images, but I can't upload them to the branch.
I'll attach them here - can you upload them, or do we need to wait until I've merged it?
When is this going to be released?

**Comment by MarkvanMents** [comment]
edit_log_level_constant
logger_edit_action

**Comment by cstevandy** [comment]
@MarkvanMents I will update the images. The new version of connector will be released after testing is done.

**Comment by MarkvanMents** [comment]
Thanks.
This looks ready to go - can you let me know when it is ready, and let me have a Release Note to go with it?
It needs a release note in the Developer Portal release notes since we announced it there when it was first released.

**Comment by MarkvanMents** [comment]
@cstevandy - I note that the document calls it SAP Logger connector, but the widget is actually called SAP LoggING connector. Shall I change this?

**Comment by cstevandy** [comment]
@MarkvanMents yes please @MarkvanMents The new version has been released: https://appstore.home.mendix.com/link/app/110219/

**Comment by MarkvanMents** [comment]
@cstevandy - I have added a release note. Can you review it, then I can merge this Pull Request.

**Comment by cstevandy** [comment]
good to go @MarkvanMents

**Pull request merged**
