### PR TITLE
Add missing cluster leader task

### PR DESCRIPTION
**Pull request by hugomendix**
This task was added in Mendix 8.13.0.

### CODE REVIEW

**Comment by MarkvanMents** [comment]
@hugomendix 
Hi Hugo,
I assume that this needs to be added to the refguide8 version of the document as well?

**Comment by hugomendix** [comment]
@MarkvanMents Yes, we simply forgot to add this to the documentation when we added this action to the cluster management.

**Comment by MarkvanMents** [comment]
OK - I'll publish this and add the same information for Mx 8.13.0 and above.

**Review by MarkvanMents — APPROVED** [review]

**Comment by MarkvanMents** [comment]
See also: https://github.com/mendix/docs/commit/216f603f17c0144b4afa8d77fde1f5bbee20d015

**Pull request merged**
