### PR TITLE
docs: add new request headers

### PR DESCRIPTION
**Pull request by Infra-Red**
Document the new Cloud v4 headers.

### CODE REVIEW

**Review by pommi — APPROVED** [review]

**Review by MarkvanMents — APPROVED** [review]
Hi Andrei, (@Infra-Red )
This looks good. Can you let me know:
1. Whether this needs a release note
2. When it can be published.
Thanks.

**Comment by Infra-Red** [comment]
@MarkvanMents We can already publish this. We can also add a release note for this change and mention that two additional header are available for the Mendix apps when using client certificates.

**Comment by MarkvanMents** [comment]
@Infra-Red 
Hi Andrei,
I've added a release note. Can you quickly review it, then I can publish.
Thanks.

**Comment by Infra-Red** [comment]
@MarkvanMents Looks good to me 👍

**Pull request merged**
