### PR TITLE
Solution upgrade documentation

### PR DESCRIPTION
**Pull request by mikita-haurykau**
Refguide update for Solution Upgrades.

Development Documentation Root page
https://mendix.atlassian.net/wiki/spaces/SOLP/pages/2175336525/Solutions+Upgrade

### CODE REVIEW

**Comment by mikita-haurykau** [comment]
CC: @rik-bos @dlhartveld

**Comment by mikita-haurykau** [comment]
@Adam-Dupaski could you please add a "nota bene" to thesol-upgrade page?
{{% alert color="info" %}} NB: you can skip versions when upgrading. E.g. if you set-up your solution with v1, then ISV released v2 and v3 it is not necessary for you to upgrade one by one. You can go directly from v1 to v3 if there was no data migration changes in v2.

Please ask your ISV about this.{{% /alert %}}

**Comment by Adam-Dupaski** [comment]
@mikita-haurykau done, thanks: https://github.com/mendix/docs/pull/5353/commits/9c1d7741629dce1e1fcc46a06f04ecdddfc3cd50

**Comment by Adam-Dupaski** [comment]
@mikita-haurykau can this be merged or does it need further review?

**Comment by Adam-Dupaski** [comment]
@mikita-haurykau and do you know when the "Upgrade solution" button will be available in SP?

**Comment by mikita-haurykau** [comment]
Hi
This should’ve been merged for 9.21 :) so you can merge it now.

**Comment by mikita-haurykau** [comment]
The button is already there if you specify `--enable-protected-modules` feature flag. People who use it are already aware of that flag so there is no need to mention it in the documentation.

**Comment by Adam-Dupaski** [comment]
Thanks @mikita-haurykau - I will merge.

Will the "Upgrade solution" button ever be available GA? Or just as a feature-flag?

**Pull request merged**
