### PR TITLE
Update Transporting a Deployment Package error messages

### PR DESCRIPTION
**Pull request by SwapnilThange**
Updated deploy API Specs

### CODE REVIEW

**Review by MarkvanMents — APPROVED** [review]
Looks good. Approving.
@SwapnilThange - Hi Swapnil - can this be published immediately?
@Luyao-Zhang-1 - Luyao, for your information as it is related to APIs and is the sort of situation that we may need to cover in the future.
Mark

**Comment by SwapnilThange** [comment]
@MarkvanMents Let's wait for API changes to be released. I will let know here once released

**Comment by MarkvanMents** [comment]
Thanks Swapnil (@SwapnilThange). We'll wait to hear from you.
In the meantime, can you check if you have signed the CLA? It says you haven't, but we've been having issues with it not always registering properly.
image

Thanks.

**Comment by SwapnilThange** [comment]
@MarkvanMents signed the agreement!

**Comment by MarkvanMents** [comment]
@SwapnilThange - do you have a date for this?

**Comment by SwapnilThange** [comment]
Hi @MarkvanMents the changes are in https://mendix.atlassian.net/browse/DEP-4617 . it is planned for the next release. which will be in two weeks from today. Due to some issues found we were not able to release it today

**Comment by MarkvanMents** [comment]
Confirmed that this has been released. Merging.

**Comment by SwapnilThange** [comment]
Thanks, Mark

**Pull request merged**
