### PR TITLE
[RUN-3891] Clarify standard format in docs about datetime formatting

### PR DESCRIPTION
**Pull request by atennapel**

### CODE REVIEW

**Comment by lvanengelen** [comment]
Should we add this caveat also to the `parseDecimal` and `parseInteger` functions? Do we need to verify whether the behavior is different between microflows and nanoflows?

**Comment by atennapel** [comment]
I updated the PR to handle 8 and 9 as well, and also Decimal formatting.

**Comment by emirmx** [comment]
Looks good!

**Comment by atennapel** [comment]
@MarkvanMents it is approved from our side, so it's ready for the docs team :)

**Comment by MarkvanMents** [comment]
> @MarkvanMents it is approved from our side, so it's ready for the docs team :)

Thanks. At least I won't start reviewing this one too early 😂

**Review by MarkvanMents — APPROVED** [review]
Thanks for the PR, Albert.
Looks like it can be published immediately, so approving and merging.

**Comment by atennapel** [comment]
Thank you, yes this one can be merged immediately.

**Pull request merged**
