### PR TITLE
Updated support page

### PR DESCRIPTION
**Pull request by mengdix**
@katarzyna-koltun-mx Updated Support Page

### CODE REVIEW

**Comment by katarzyna-koltun-mx** [comment]
@mengdix I've reviewed the update and it looks good. Jean also approved it. I have 1 question - why is "Certified" and "Partner" put in brackets in lines 121 and 122?

**Comment by mengdix** [comment]
> @mengdix I've reviewed the update and it looks good. Jean also approved it. I have 1 question - why is "Certified" and "Partner" put in brackets in lines 121 and 122?

@katarzyna-koltun-mx Parts of this component are supported directly by product, others require investigation with Partners first. Principally Partners are always first line of support.

**Comment by katarzyna-koltun-mx** [comment]
@mengdix So should "(Certified) Mendix (Partners)" be understood as "Mendix Support, Mendix Partners or Certified Mendix Partners"? I'd like to be explicit and the current wording is a bit ambiguous.

**Comment by mengdix** [comment]
@katarzyna-koltun-mx In the context of who to reach out to regarding issues: Certified Mendix Partners

**Comment by katarzyna-koltun-mx** [comment]
@mengdix Got it, in that case I've removed the brackets and will publish directly.

**Pull request merged**
