### PR TITLE
[RTI-338] Add Task Queue Retry to docs

### PR DESCRIPTION
**Pull request by atennapel**

### CODE REVIEW

**Comment by atennapel** [comment]
Note: this is no longer for 9.9.0 but for 9.10. I still have to update the docs here.

**Review by MarkvanMents — APPROVED** [review]
Added note that these are only available after 9.9.0,
tried to clarify exactly what the options are - particularly for exponential retry.
Thanks for the PR, @atennapel

**Comment by MarkvanMents** [comment]
Is this still in draft, or can I convert it to ready for review?

**Comment by atennapel** [comment]
Thanks Mark, it's still in draft currently. Because we missed the 9.9.0 freeze we are now aiming for 9.10.0. So I still need to update the docs because we have changed some more things.

**Comment by atennapel** [comment]
I have updated the MR for Mx 9.10.

**Review by MarkvanMents — APPROVED** [review]
Reviewed changes. Looks good.

**Pull request merged**
