### PR TITLE
Update migrating-to-v4.md

### PR DESCRIPTION
**Pull request by JeffreyMansystems**
Switched Backing Up and Downloading and Uploading the Deployment Package. Current workflow generates an error when uploading the backup.

### CODE REVIEW

**Comment by MarkvanMents** [comment]
@JeffreyMansystems

Thanks for your contribution.

Please could you click to sign the Contributor License Agreement (click on **Details** next to the *clahub* check). I realize that in this case you haven't actually changed any wording, but signing the cla means that it is clearer which pull requests will merge successfully.

Thanks

Mark

**Comment by MarkvanMents** [comment]
@manreet185 

Could someone in your team review this please? Looks like it will work, but I'd like confirmation from you before publishing.

Thanks

**Comment by JeffreyMansystems** [comment]
Hi Mark, thanks for looking into this. I've signed the CLA.

**Comment by MarkvanMents** [comment]
Have confirmed that this is a known problem.

**Comment by JeffreyMansystems** [comment]
@MarkvanMents, thanks for letting me know that the change is confirmed.

**Pull request merged**
