### PR TITLE
updated release notes

### PR DESCRIPTION
**Pull request by GautamJ700**
Explicitly mentioned support for Mendix 10

### CODE REVIEW

**Comment by MarkvanMents** [comment]
@GautamJ700 - Can you give me access to edit your pull request as there are a couple of formatting changes I'd like to make before merging. See https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork for more information.
image
Thanks.

**Comment by GautamJ700** [comment]
HI @MarkvanMents  I cannot see the options "Allow edits from maintainers". I believe the repository owner need to enable this feature , and the owner is on holiday and will be back next week.

**Comment by MarkvanMents** [comment]
@GautamJ700 
Thanks for getting back to me.
I think you should be able to set this option for each individual Pull Request - to the right of this comment at the bottom of the list of Reviewers, Assignees, Labels, etc. I don't think it needs to be set for the entire fork. But perhaps there is some setting on the fork which is overriding this.

Can you have one more look. If you can't change it today I'll merge your changes tomorrow and then do the formatting afterwards.

**Review by MarkvanMents — APPROVED** [review]
Approving for merge,
Will merge into a different branch and then follow up and update the file to use the correct markdown styles
Cannot do this on the PR as I don't have access to edit the file on the fork.

**Pull request merged**
