### PR TITLE
Move guidelines custom action to howtos

### PR DESCRIPTION
**Pull request by zwartd**

### CODE REVIEW

**Comment by Adam-Dupaski** [comment]
Hi @zwartd, please sign the [CLA](https://www.clahub.com/agreements/mendix/docs), this is required for merging all pull requests.

**Comment by Adam-Dupaski** [comment]
Hi @zwartd and @myrthewalhout, please sign the [CLA ](https://www.clahub.com/agreements/mendix/docs) if you have not already, this is required for merging pull requests. Thanks.

**Comment by Adam-Dupaski** [comment]
Hi @zwartd and @myrthewalhout, when is this PR supposed to be merged and published? Because PRs 781, 788, 789, and 790 are still labeled as "Future release" and so still need to be merged - but there are overlaps with this PR (i.e., all of the .PNGs are also in PR 795, and ht-version-1.md is in PR 795 with the same changes).

**Comment by zwartd** [comment]
Hi @Adam-Dupaski ,
Myrthe and i both signed the CLA. 

This pr can be published directly, the other pr's are waiting for the ATS 2 release. The documentation in this pr only concerns ATS 1. The overlapping with pr 795 is only for ATS 1 documentation, is that a problem? (Just asking since i honestly don't know). Just let me know!

**Comment by Adam-Dupaski** [comment]
Hi @zwartd, thanks for the comments. I have reviewed the changes here, and I question the purpose of moving "Guidelines for Creating a Custom Action" from Best Practices to How-to's. This is clearly a best practices doc: it is written as "guidelines" and not as a steps for a how-to; it does not use the how-to template at all and lists no steps for accomplishing specific goals. In my view, this should stay as a Best Practices type of doc, because it is clearly a set of best practices. Please let me know what you think. Thanks.

**Comment by zwartd** [comment]
Hi Adam,
The reason we were thinking of moving the file is because it is only used in the custom action how-to section. So we thought it might be more logical for users if the file would also be there. But i understand that the file fits better in the best practice section. I will discuss it with my colleagues and come back to you.

**Comment by zwartd** [comment]
Hi @Adam-Dupaski,
We believe that it is better for the users if the document goes to the how-to section. Making it easier to understand the overall structure of the custom action documentation. However, we understand that the document does not really fit in. Would it be better if i restructure it so that it fits in better with the rest? Please let me know!

**Comment by Adam-Dupaski** [comment]
Hi @zwartd, thanks for the reply. If the Guidelines doc is relevant only to the Create Custom Actions how-to's, then it could probably go in Create Custom Actions > General. In that section, you have the Helpful Resources, Structure, and Prerequisites docs - so a Guidelines doc could also be a good fit there. Would that work?

**Comment by zwartd** [comment]
@Adam-Dupaski yea that would be great.

**Pull request merged**
