### PR TITLE
Extend navigation profiles in Mx7.4

### PR DESCRIPTION
**Pull request by r0b1n**
Because of changes in navigation profiles in Mendix 7.4 we need to update some related docs.

### CODE REVIEW

**Comment by Adam-Dupaski** [comment]
Hi Roman, please take a minute to sign the [CLA ](https://www.clahub.com/agreements/mendix/docs) (even though you are Mendix internal).
Thanks.

**Comment by Adam-Dupaski** [comment]
This should only be published upon release of 7.4.0, correct?

**Comment by Adam-Dupaski** [comment]
Build passed.

**Comment by r0b1n** [comment]
Hi Adam. Yes, this should be published together with 7.4.0 release.

**Pull request merged**
