### PR TITLE
Conversational Design Checklist updates

### PR DESCRIPTION
**Pull request by Karuna-Mendix**

### CODE REVIEW

**Comment by Karuna-Mendix** [comment]
Hi Insuk Ko, can you please provide me a correct image for section 6.3 (first image)? There is a typo in the current image (ypu).

**Comment by Ichigoko** [comment]
> Hi Insuk Ko, can you please provide me a correct image for section 6.3 (first image)? There is a typo in the current image (ypu).

LUC1

**Comment by Ichigoko** [comment]
> Hi Insuk Ko, can you please provide me a correct image for section 6.3 (first image)? There is a typo in the current image (ypu).

image

**Review by Ichigoko — APPROVED** [review]
Looks good. Thank you!

**Pull request merged**
