### PR TITLE
Change Mendix Developer App reference to the Mendix App for 7.6

### PR DESCRIPTION
**Pull request by mlaponder**
The Mendix Developer App functionality is now integrated in the Mendix App. This merge request replaces the references from Mendix Developer App to the Mendix App.

### CODE REVIEW

**Comment by mlaponder** [comment]
Please merge this when 7.6 is released.

**Comment by Adam-Dupaski** [comment]
1. I would like to discuss the naming of this app. "Mendix App" seems less recognizable and easy for the user than "Mendix Developer." Most apps do not have "App" in their title. It is also more difficult to clearly document: there can be confusion between "Mendix App" and "Mendix app" (i.e., an app developed in Mendix). Calling it "the Mendix App mobile app" is not a good option. Is it possible to discuss/update this naming?

2. Developing a Hybrid Mobile App: has the "View Hybrid Mobile App" button name been changed to "Mendix Developer App"? The documentation has not been updated. Will it stay like this? We need to update the docs in this pull request and all other instances.

3. How to Deploy Your First Hybrid Mobile App: this doc needs to be updated for the naming of the app and also for the "View Hybrid Mobile App" button name (see above).

4. Getting the Mendix Mobile App: this doc should be deleted upon 7.6.0 release, correct?

5. Getting the Mendix Developer App: this doc needs to be verified and updated. Can you verify that the details will still be accurate?

Please let me know, we can work on this together. Thanks.

**Comment by Adam-Dupaski** [comment]
Before making any new commits for more doc changes, please pull development changes into your branch and rebase. The merge conflicts need to be resolved before 7.6.

**Comment by Adam-Dupaski** [comment]
Marco, thanks for the changes. Two more questions:

- Developing Hybrid Mobile Apps - section 2: mentions the "View Hybrid Mobile App" button - is this correct? I thought this button didn't exist anymore and was replaced by the "Hybrid Tablet/Phone App Online" buttons. Or is this supposed to be the "View in the Mendix App" button?
- Getting the Mendix App document: any updates necessary for this document? Please verify the platform version specs.

**Comment by Adam-Dupaski** [comment]
Before merging, update "Deploy Your First Hybrid Mobile App" - change "getting-the-mendix-developer-app" reference to "getting-the-mendix-app".

**Comment by Adam-Dupaski** [comment]
After merging, update "How to Deploy Your First Hybrid Mobile App" with new app info.

**Comment by Adam-Dupaski** [comment]
After merging, verify screenshots of app "How to Deploy Your First Hybrid Mobile App."

**Comment by Adam-Dupaski** [comment]
After merging, verify name of app (in app stores) and adjust documentation if necessary.

**Comment by Adam-Dupaski** [comment]
After merging, verify screenshots of View menu (app choice).

**Pull request merged**
