### PR TITLE
Datahub external release notes update for 2.24.1 hotfix

### PR DESCRIPTION
**Pull request by ahmbataslan**

### CODE REVIEW

**Comment by Adam-Dupaski** [comment]
Hi @ahmbataslan this is being released today? What time?

**Comment by ahmbataslan** [comment]
It will be released today after 8 pm

**Review by Adam-Dupaski — APPROVED** [review]

**Comment by Adam-Dupaski** [comment]
@ahmbataslan so I will publish now.

**Comment by Adam-Dupaski** [comment]
@johannahemminger to review upon return.

**Comment by ahmbataslan** [comment]
Hi Adam, yes I work for Mendix. You can look for me as Batuhan Aslan. I had to log in with my personal github address for Mendix Docs, that's what they told me in the first place, and it stayed like that. Sorry for the confusion.

**Pull request merged**
