### PR TITLE
Support for OAuth 2.0 in IMAP/POP3 connector

### PR DESCRIPTION
**Pull request by johannahemminger**

### CODE REVIEW

**Comment by johannahemminger** [comment]
@rover886 could you take a look at the section I added here?

**Comment by rover886** [comment]
@johannahemminger are we going to put an image at "2.2.1 Enable Permissions" ? if yes then use below image 
image

**Comment by rover886** [comment]
At the start of 2.2 can we mention that "This is currently only available with module version 4.1.0 for MX 7.23.31 (LTS) and soon made available with other versions. "

**Comment by rover886** [comment]
Add one more point:

2.2.4 After Startup Microflow

1. In the App Explorer, go to Settings to open the App Settings dialog box.
2. Go to the Runtime tab.
3. For After startup, Select the `ASU_RegisterHandlers` microflow.

**Comment by rover886** [comment]
@johannahemminger Add below point as well (may be after the line `To register your app, follow Microsoft's..`)

While registering the app on Azure portal make sure that the callback URL is set to https://(yourapp_domain)/callback/azure

**Comment by rover886** [comment]
Hey @johannahemminger This looks perfect now. Reviewed with Goraksh and Pramod as well, lets merge it with master now. Thanks :)

**Pull request merged**
