### PR TITLE
Update Mendix 7.4 release notes for Runtime.

### PR DESCRIPTION
**Pull request by jveldhuizen**

### CODE REVIEW

**Comment by jveldhuizen** [comment]
Sorry for these release notes now. We completely forgot to add them earlier before the release.

**Comment by Adam-Dupaski** [comment]
Jonathan, please sign the [CLA](https://www.clahub.com/agreements/mendix/docs).
Thanks.

**Comment by jveldhuizen** [comment]
Hi Adam,

I’m not sure what I have to sign, because it is in English and that is more difficult for me. Maybe Jan can explain it to me.

What should I fill in in the ‘Corporate Contributor Information’ field?

Regards,

Jonathan

Van: Adam Dupaski [mailto:notifications@github.com]
Verzonden: woensdag 5 juli 2017 10:57
Aan: mendix/docs <docs@noreply.github.com>
CC: Jonathan Veldhuizen <Jonathan.Veldhuizen@mendix.com>; Author <author@noreply.github.com>
Onderwerp: Re: [mendix/docs] Update Mendix 7.4 release notes for Runtime. (#539)


Jonathan, please sign the CLA<https://www.clahub.com/agreements/mendix/docs>.
Thanks.

**Comment by Adam-Dupaski** [comment]
Hi Jonathan, you can just write something simple like "Yes."
Thanks.

**Pull request merged**
