### PR TITLE
APM 1.12

### PR DESCRIPTION
**Pull request by TolenE**
A new release for APM

The release is ready, so documentation can go online

### CODE REVIEW

**Comment by TolenE** [comment]
Hi Adam,

1.11==1.12 except Mx6 vs Mx7

Verstuurd vanaf mijn iPhone

Op 6 apr. 2017 om 16:30 heeft Adam Dupaski <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


@Adam-Dupaski requested changes on this pull request.

  1.  The 1.11 release notes mention release 1.12, which they should not - release notes should not compare a current release to a future release. What was done for 1.11? There are no actual release notes. Should the notes from 1.12 be copied in for 1.11, with the specification that 1.11 is for Mendix 6.2+ and 1.12 is for Mendix 7.0.2?
  2.  If 1.12 is for Mendix 7.0.2, that should be specified in the RN. Can you please verify that?
  3.  I do not see a "Running microflows" tab in the statistics tool on any screenshot and it does not appear in the documentation. Is that the correct name, or should it be "Running actions"?
  4.  "Statistics and message triggers did not stop after firing when configured to do so." - there is no resolution here. Should it just be "We fixed this"?
  5.  This sentence is unclear: "To prevent running out of memory, the performance tool now stops recording at 80% memory usage and cancel and thus free memory at 95% memory usage." Specifically, "and cancel" and "thus free memory at 95% memory usage." Where are the verbs here? Please clarify.

**Comment by TolenE** [comment]
Diff versions for appstore on request andrej

Verstuurd vanaf mijn iPhone

Op 6 apr. 2017 om 16:30 heeft Adam Dupaski <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


@Adam-Dupaski requested changes on this pull request.

  1.  The 1.11 release notes mention release 1.12, which they should not - release notes should not compare a current release to a future release. What was done for 1.11? There are no actual release notes. Should the notes from 1.12 be copied in for 1.11, with the specification that 1.11 is for Mendix 6.2+ and 1.12 is for Mendix 7.0.2?
  2.  If 1.12 is for Mendix 7.0.2, that should be specified in the RN. Can you please verify that?
  3.  I do not see a "Running microflows" tab in the statistics tool on any screenshot and it does not appear in the documentation. Is that the correct name, or should it be "Running actions"?
  4.  "Statistics and message triggers did not stop after firing when configured to do so." - there is no resolution here. Should it just be "We fixed this"?
  5.  This sentence is unclear: "To prevent running out of memory, the performance tool now stops recording at 80% memory usage and cancel and thus free memory at 95% memory usage." Specifically, "and cancel" and "thus free memory at 95% memory usage." Where are the verbs here? Please clarify.

**Comment by Adam-Dupaski** [comment]
Then RN 1.11 will include all of the content and specify Mendix version 6.2+. 
RN 1.12 will say "refer to 1.11" and specify Mendix version 7.0.2+.

**Comment by Adam-Dupaski** [comment]
Please comment on the remaining comments in order to finish this merge:

 3. I do not see a "Running microflows" tab in the statistics tool on any screenshot and it does not appear in the documentation. Is that the correct name, or should it be "Running actions"?
4. "Statistics and message triggers did not stop after firing when configured to do so." - there is no resolution here. Should it just be "We fixed this"?
5. This sentence is unclear: "To prevent running out of memory, the performance tool now stops recording at 80% memory usage and cancel and thus free memory at 95% memory usage." Specifically: 
- "and cancel" - cancel what?
- "thus free memory at 95% memory usage." - unclear how this relates to "80% memory usage and cancel"

**Comment by TolenE** [comment]
Hi Adam,

I’m now in the office, so let me answer all items.

As said before, Andrej requested to separate releases, because the AppStore cannot upload 2 identical releases for different Mendix versions.

@3: Should be “Running actions”

@4: We fixed this and they now stop.

@5: Cancel = Cancel the recording. At stop recording no new data is recorded, at cancel all recorded data is thrown away. So at 80% it stops recording and you can still save that. If, due to other non APM functionality – memory goes over 95%, all memory claimed by the performance tool is freed by cancelling the recording and throwing away recorded data.

Best regards,

Bart

**Pull request merged**
