### PR TITLE
How to configure Json logging.

### PR DESCRIPTION
**Pull request by serg-firsov**

### CODE REVIEW

**Comment by katarzyna-koltun-mx** [comment]
@serg-firsov Hi Sergey! I'll be reviewing your PR. I've noticed that there seem to be some extra } characters in some of the code blocks (lines 548, 574, 601, 602, 632). Could you verify?

Also, your github account doesn't have the Mendix CLA signed. Could you sign it?

**Comment by atennapel** [comment]
Looks good to me, from a technical side.

**Comment by serg-firsov** [comment]
Hi @katarzyna-koltun-mx,

> @serg-firsov Hi Sergey! I'll be reviewing your PR. I've noticed that there seem to be some extra } characters in some of the code blocks (lines 548, 574, 601, 602, 632). Could you verify?

I didn't find extra } characters, but I noticed that I used single quotes while double quotes are used in the rest of the document, so I changed single quotes to double quotes to make it consistent.

> Also, your github account doesn't have the Mendix CLA signed. Could you sign it?

I just did singn the Mendix CLA, but it still shows that it's not signed.

**Comment by katarzyna-koltun-mx** [comment]
@serg-firsov Thank you! I'll merge your PR now.

**Pull request merged**
