### PR TITLE
Unlimited and Very long Strings behavior on DBs

### PR DESCRIPTION
**Pull request by pouyaist**

### CODE REVIEW

**Comment by Adam-Dupaski** [comment]
Hi Pouya, please sign the [CLA](https://www.clahub.com/agreements/mendix/docs).

**Comment by Adam-Dupaski** [comment]
Is this for 7.23.4 and also Mx8?

**Comment by pouyaist** [comment]
> Is this for 7.23.4 and also Mx8?

this is for Mx8

**Comment by pouyaist** [comment]
> Hi Pouya, please sign the [CLA](https://www.clahub.com/agreements/mendix/docs).

This is a personal account, I don't see the point to authorize someone else on it.

**Comment by Adam-Dupaski** [comment]
> This is a personal account, I don't see the point to authorize someone else on it.

It is not clear what you mean by "personal account" nor what you mean by "authorize someone else on it." You are not authorizing anyone else, you are signing a legal agreement to contribute to the documentation.

**Comment by Adam-Dupaski** [comment]
> 
> 
> > Is this for 7.23.4 and also Mx8?
> 
> this is for Mx8

This repo has Mx7 docs, so this PR is for Mx7. If you need to contribute to Mx8 docs, you need to send a merge request to the GitLab repo. Please see my email from 3.11.

**Comment by pouyaist** [comment]
> Is this for 7.23.4 and also Mx8?

I double checked we already released it in 7.23.3. Thus, it is for Mendix 7

**Pull request merged**
