### PR TITLE
Corrected code error and incorrect image

### PR DESCRIPTION
**Pull request by gitsno**
Corrected the image for step 1. in "3.5 Making the Input Labeled" and corrected the code in step 2. of "3.6 Handling Updates".

### CODE REVIEW

**Comment by ConnorLand** [comment]
Hi @gitsno. Thank you for your contribution. We are going to merge your code change. However, did you mean to upload a "corrected" image in 3.5? I don't see an image file change. Thank you!

**Comment by gitsno** [comment]
Sorry about that, I guess I didn't have it in this original PR - I just created a new PR that does have that file.

**Comment by ConnorLand** [comment]
This code change has been verified and will be merged. This change will prevent IDE warning messages, and make the code clearer for other users.  Thank you for your contribution.

**Comment by ConnorLand** [comment]
This PR addresses the 432766 feedback item.

**Pull request merged**
