### PR TITLE
Just a note for debugger-settings-saps4hana.png

### PR DESCRIPTION
**Pull request by TimvanSteenbergen**
debugger-settings-saps4hana

### CODE REVIEW

**Comment by MarkvanMents** [comment]
Developer team asked for technical confirmation.

**Comment by zlogic** [comment]
Looks good to me.

**Comment by MarkvanMents** [comment]
Thanks

**Comment by MarkvanMents** [comment]
Merging to new branch so I can add missing image

**Comment by MarkvanMents** [comment]
@TimvanSteenbergen 
Thanks for your input, Tim. Your changes have been merged and will be published in the next 24 hours.

**Pull request merged**
