### PR TITLE
SAP Odata Connector Reference

### PR DESCRIPTION
**Pull request by MarkvanMents**
Completely re-written

### CODE REVIEW

**Comment by Adam-Dupaski** [comment]
@MarkvanMents Please redo these screenshots for the Modeler modernization in 7.12.

**Comment by Adam-Dupaski** [comment]
@MarkvanMents Please check the Travis error log and fix the build error.

**Comment by MarkvanMents** [comment]
@Adam-Dupaski has 7.12 still got a release date? I've just seen that all the dates have changed. I didn't want this sitting for a month before it goes live.
I will do the 7.12 pictures as a new pull, if that is OK.
Am checking the Travis log as I write.

**Comment by Adam-Dupaski** [comment]
@MarkvanMents The release of 7.12 is still on time, AFAIK. Updating the screenshots in another PR is fine. Please note that other R&D teams are updating all Ref Guide screenshots for 7.12, so your team should plan for that for SAP-related Ref Guide docs. Thanks for fixing the build error.

**Comment by MarkvanMents** [comment]
@Adam-Dupaski 
OK - doing the new screenshots now, plus the other ones on the spreadsheet

**Comment by Adam-Dupaski** [comment]
@MarkvanMents Sounds good, thanks.

**Pull request merged**
