### PR TITLE
Updated specs to Java 11 for Mx8

### PR DESCRIPTION
**Pull request by grootjans**
Update for our migration from the current LTS (8) to the new LTS (11).

Should also be approved by @ironthorn with respect to the MxBuild spec changes.

### CODE REVIEW

**Comment by Adam-Dupaski** [comment]
@grootjans & @ironthorn this is for the Beta 3 release, correct?

**Comment by Adam-Dupaski** [comment]
@ironthorn please verify this commit: https://github.com/mendix/docs/pull/1711/commits/8e1728f7ccf982f0658c97e5cf8380b8083a602b

**Comment by ironthorn** [comment]
Paul Rijneveld (at conference) and Gulam are working on the upgrade of the JDK so they know best.

**Comment by Adam-Dupaski** [comment]
Section 2 update approved by Gulam

**Pull request merged**
