### PR TITLE
[SOLP-2210] Adding info about index.lock file for VC

### PR DESCRIPTION
**Pull request by blis-mendix**

### CODE REVIEW

**Comment by MariaShaposhnikova** [comment]
@blis-mendix , thank you for the PR. Is this change tied up to any particular SP version?

**Comment by blis-mendix** [comment]
> @blis-mendix , thank you for the PR. Is this change tied up to any particular SP version?

Hey! No, not really it's an issue that can happen any time with git.

**Comment by MariaShaposhnikova** [comment]
@blis-mendix , thanks for the explanation! I've reviewed it, could you take a look and let me know if you have any questions and comments? And afterwards, I will merge it to production.

**Comment by blis-mendix** [comment]
> @blis-mendix , thanks for the explanation! I've reviewed it, could you take a look and let me know if you have any questions and comments? And afterwards, I will merge it to production.

Looks great! Thanks for corrections!

**Pull request merged**
