### PR TITLE
Document support Mendix versions on Mendix Cloud

### PR DESCRIPTION
**Pull request by feddovanede**
Document support Mendix versions on Mendix Cloud

### CODE REVIEW

**Comment by feddovanede** [comment]
@grootjans could you review?

**Comment by feddovanede** [comment]
@MarkvanMents Is this the right place to document this?

**Comment by MarkvanMents** [comment]
> @MarkvanMents Is this the right place to document this?

Hi @feddovanede 
Looks like the right place to document it. Should we also have it as a prerequisite here: https://docs.mendix.com/developerportal/deploy/mendix-cloud-deploy/deploying-an-app/#prerequisites ?

**Comment by feddovanede** [comment]
@MarkvanMents Yes, that makes sense! Added that to the PR.

**Comment by MarkvanMents** [comment]
> @grootjans could you review?

Are we still waiting for Robbert Jan to review?

**Review by MarkvanMents — APPROVED** [review]
Looks good.
Release Approved over Slack.

**Pull request merged**
