### PR TITLE
Update how to download a backup

### PR DESCRIPTION
**Pull request by katamaks**
changed project to app

### CODE REVIEW

**Comment by jtwaleson** [comment]
@Adam-Dupaski can you merge?

**Comment by katamaks** [comment]
Please change "Under Operate click Backups" into "Click **Backups** under the **Operate** category" before merging

**Comment by Adam-Dupaski** [comment]
@katamaks You can add another commit with that and any other changes necessary. :)

**Comment by katamaks** [comment]
@Adam-Dupaski I just did it. I also added an image but I was unable to add a new folder to the attachments

**Comment by Adam-Dupaski** [comment]
@katamaks If you are not using SourceTree, probably the easiest thing to do is to drag-drop the image file/sub-folder to the correct folder location in GitHub (in the browser here). Commit that and send another pull request with that image, which I will merge. After merging that, this current pull request should be okay to merge (as of now it cannot be merged because it will break the build).

**Comment by Adam-Dupaski** [comment]
Or, if you drag-drop the image file to a folder on your branch, it should add that commit to this pull request.

**Comment by katamaks** [comment]
environment

**Pull request merged**
