### PR TITLE
Add PWA table with most common features

### PR DESCRIPTION
**Pull request by diego-antonelli**

### CODE REVIEW

**Review by Keraito — APPROVED** [review]
Was the "Contacts" feature left out on purpose @diego-antonelli

**Comment by diego-antonelli** [comment]
> Was the "Contacts" feature left out on purpose @diego-antonelli

Yes, its currently just a draft

**Review by ConnorLand — APPROVED** [review]

**Comment by ConnorLand** [comment]
> > Was the "Contacts" feature left out on purpose @diego-antonelli
> 
> Yes, its currently just a draft

Hi @diego-antonelli . Please let me know when this draft is safe for publishing.

**Comment by diego-antonelli** [comment]
@ConnorLand this will not be included, when i said Draft, it was a proposal to be included in browsers, not in this PR.

**Pull request merged**
