### PR TITLE
Update date-creation.md

### PR DESCRIPTION
**Pull request by Ruud279b**
Small change to date settings. These only apply to scheduled events.

### CODE REVIEW

**Comment by Adam-Dupaski** [comment]
@Ruud279b Please sign the [CLA](www.clahub.com/agreements/mendix/docs).

**Comment by Ruud279b** [comment]
> 
> 
> @Ruud279b Please sign the [CLA](www.clahub.com/agreements/mendix/docs).

Done!

**Comment by Adam-Dupaski** [comment]
> 
> 
> > @Ruud279b Please sign the [CLA](www.clahub.com/agreements/mendix/docs).
> 
> Done!

The check below is saying it is still not signed. :)

**Comment by Ruud279b** [comment]
> > > @Ruud279b Please sign the [CLA](www.clahub.com/agreements/mendix/docs).
> > 
> > 
> > Done!
> 
> The check below is saying it is still not signed. :)

Yep, should be OK now.

**Comment by Adam-Dupaski** [comment]
Thanks for the PR.

**Pull request merged**
