### PR TITLE
Update user task properties

### PR DESCRIPTION
**Pull request by timvandervoornmx**

### CODE REVIEW

**Comment by MariaShaposhnikova** [comment]
Hi @timvandervoornmx , 
For what version is this PR?

**Comment by timvandervoornmx** [comment]
It’s for 9.21 😊

From: Maria Shaposhnikova ***@***.***>
Date: Friday, 16 December 2022 at 16:58
To: mendix/docs ***@***.***>
Cc: Tim van der Voorn ***@***.***>, Mention ***@***.***>
Subject: Re: [mendix/docs] Update user task properties (PR #5436)

Hi @timvandervoornmx<https://github.com/timvandervoornmx> ,
For what version is this PR?

**Comment by MariaShaposhnikova** [comment]
@timvandervoornmx , we do not use dark mode for our screenshots. Can you please replace the updated screenshot with the light mode one?

**Comment by timvandervoornmx** [comment]
@MariaShaposhnikova Done!

**Pull request merged**
