### PR TITLE
Private Cloud - Release Notes (7 September)

### PR DESCRIPTION
**Pull request by Nidhi251289**
Added the release notes for 27 August release

### CODE REVIEW

**Comment by Adam-Dupaski** [comment]
@Nidhi251289 please sign the CLA (new app was needed): https://cla-assistant.io/mendix/docs?pullRequest=2678

**Comment by Nidhi251289** [comment]
CLA signed

**Comment by Adam-Dupaski** [comment]
@MarkvanMents please review upon return

**Review by Adam-Dupaski — APPROVED** [review]

**Comment by Adam-Dupaski** [comment]
@MarkvanMents passing this back to you, they will let you know when to publish.

**Pull request merged**
