### PR TITLE
External entities do not require a separate license anymore

### PR DESCRIPTION
**Pull request by joostverhoog**

### CODE REVIEW

**Review by MarkvanMents — COMMENTED** [review]
@joostverhoog 

Thanks for the PR.

I found another reference to licensing Data Hub and have removed that. Is that correct, or is this about something else?

There is also [a reference to needing a license to have your published OData service appear in the catalog](https://docs.mendix.com/refguide/wrap-services-odata/#22-compatibility-with-data-hub). Is this limitation also removed?

Let me know, and I can publish this once I know that the changes are accurate.

**Comment by joostverhoog** [comment]
> There is also [a reference to needing a license to have your published OData service appear in the catalog. Is this limitation also removed?

Yes, that's indeed correct, that limitation has been removed as well.

**Comment by MarkvanMents** [comment]
> > There is also [a reference to needing a license to have your published OData service appear in the catalog. Is this limitation also removed?
> 
> Yes, that's indeed correct, that limitation has been removed as well.

Great. I've updated the text in this commit: https://github.com/mendix/docs/pull/6457/commits/1660f57f9e7c9663e396c5dc6d7fa813dea8348a

Let me know if you are happy with the changes and I'll publish them.

**Comment by MarkvanMents** [comment]
Taking it from the smiley face that you are happy - resolving conflict and merging.

**Review by MarkvanMents — APPROVED** [review]
Thanks for the PR, Joost.
Approving and merging.

**Pull request merged**
