### PR TITLE
Restructure Release Notes

### PR DESCRIPTION
**Pull request by Luyao-Zhang-1**

### CODE REVIEW

**Comment by Luyao-Zhang-1** [comment]
@MarkvanMents  @MariaShaposhnikova  Currently, the Release Notes of the Extensibility API and ATS are not in the **Release Notes** space. I moved their Release Notes here, putting them under the **Studio Pro** category and the **Marketplace** category, respectively (which aligns with the location of these docs). Based on Mark's feedback, I also move **Mx10 Feature Release Calendar** downwards. You can find the preview of the new structure in the screenshot below. 

Could you please take a look at the new structure and let me know if you have any comments?

image

**Comment by MariaShaposhnikova** [comment]
@Luyao-Zhang-1 , this is a great improvement! 
Some suggestions:
1. We have SDK and APIs grouped together as a space (**APIs and SDK**), should we have the same structure in the **Release Notes** space and move **Extensibility API** under **SDK** (and rename it to **APIs and SDK**?)
2. Should Marketplace RN have two child sub-categories? The existing ones will become a sub-category (for example, General Marketplace RN and ATS). I hope it is clear what I mean.

**Comment by Luyao-Zhang-1** [comment]
@MariaShaposhnikova Thank you for your input. I think they are both good ideas!

**Comment by Luyao-Zhang-1** [comment]
Closing this PR due to too many merge conflicts. Created a [new PR ](https://github.com/mendix/docs/pull/8631)and continue the work from there.

**Pull request closed without merging**
