### PR TITLE
Update custom-error-page.md

### PR DESCRIPTION
**Pull request by gajduk-mansystems**
Removed *s* from error_page everywhere, "error_page" is correct

Also added comment to calrify that the change is not immediaty accoring to this forum post - https://forum.mendixcloud.com/link/questions/87752  (answered by verified mendix cloud developer)

### CODE REVIEW

**Comment by Adam-Dupaski** [comment]
Hi @gajduk-mansystems, please sign the [CLA](www.clahub.com/agreements/mendix/docs) for us to merge this. Thanks.

**Comment by gajduk-mansystems** [comment]
Just signed the CLA

**Comment by gajduk-mansystems** [comment]
Just signed the CLA

**Comment by Adam-Dupaski** [comment]
@katamaks Can you please review this PR? Please contact me after.

**Comment by Adam-Dupaski** [comment]
Thanks @katamaks !

**Pull request merged**
