### PR TITLE
Android video player fullscreen styles

### PR DESCRIPTION
**Pull request by Ahmad-Elsayed**

### CODE REVIEW

**Comment by jordanch** [comment]
Approved from native content team.

**Comment by ConnorLand** [comment]
This will solve the following support ticket: https://mendix.atlassian.net/browse/NC-665

**Comment by Ahmad-Elsayed** [comment]
the widget is not yet released

**Comment by Ahmad-Elsayed** [comment]
@ConnorLand  The widget changes are scheduled to be release on Monday 28th of March

**Review by ConnorLand — APPROVED** [review]

**Pull request merged**
