### PR TITLE
No load more button for native list view

### PR DESCRIPTION
**Pull request by Andries-Smit**

### CODE REVIEW

**Comment by IntonoviPetar** [comment]
This doesn't work as described in the PR.
Please [have a look at this loom video](https://www.loom.com/share/dfff520dd87640f7a39f234114b34fe8) that showcases that it's incorrect:

**Comment by MarkvanMents** [comment]
Hi Petar (@IntonoviPetar)

Thank you for raising this. I will pass it on to the development team, to find out how it should work and whether there is an issue with this widget.

I will get back to you next week.
If this is an urgent issue, you can raise it with Mendix Support (https://support.mendix.com) so that it can go through our formal escalation procedure.

Thank you for bringing this issue to my attention.

Mark

**Comment by IntonoviPetar** [comment]
> Hi Petar (@IntonoviPetar)
> 
> Thank you for raising this. I will pass it on to the development team, to find out how it should work and whether there is an issue with this widget.
> 
> I will get back to you next week.
> If this is an urgent issue, you can raise it with Mendix Support (https://support.mendix.com) so that it can go through our formal escalation procedure.
> 
> Thank you for bringing this issue to my attention.
> 
> Mark

Hello Mark,

It's not an urgent issue, the workaround behind this was to set a limit to a bigger number than required so all the items will be loaded.
However, I believe that might impact the app performance, but I am unsure on that point.

Thank you so much, waiting on the verdict here.

**Comment by MarkvanMents** [comment]
Hi Petar (@IntonoviPetar)
I have tried to get a better answer from the developers, but they still insist that scrolling down should add new items to the list and cannot replicate your issue.

If this is still an issue for you, I suggest that you raise a ticket with Mendix Support (https://support.mendix.com) who will be able to look into it in more detail and escalate it if necessary. They may ask you for more details of the project so that they can isolate the exact circumstances which are causing this not to work.

Sorry that I was not able to get a better answer immediately.

Yours

Mark van Ments

**Comment by IntonoviPetar** [comment]
Hello Mark,

Well, the issue came up when you use nanoflow as a data source for the list. It's very easy to replicate. :)

**Comment by MarkvanMents** [comment]
Hi Petar,
Sorry to be formal about it, but I've sent your video through to the developer team and they respond that it just loads more. I've pushed them for a better answer, but haven't got one.
If you still need an answer and don't mind going via support, it will help get to the bottom of your issue and, hopefully, issues of other people who might the same problem. Support can escalate the issue if they feel that the answer they receive is inadequate. I don't have the example to give them, and it is more likely to be treated seriously if it comes from a customer.
Thanks for raising the issue, and I'm sorry that this route has not been successful in solving it.
Yours
Mark van Ments

**Pull request merged**
