### PR TITLE
RN: Extend retention of backups

### PR DESCRIPTION
**Pull request by MarkvanMents**
Update documentation and release note

### CODE REVIEW

**Comment by MarkvanMents** [comment]
We have a table with the expected times that daily backups will be taken. Should this be expanded to cover the newer centers,

-     **Mendix Cloud Asia Pacific: AWS Singapore**
-     Mendix Cloud Asia Pacific: AWS Tokyo
-     **Mendix Cloud EU: AWS Dublin**
-     Mendix Cloud EU: AWS Frankfurt
-     Mendix Cloud UK: AWS London
-     Mendix Cloud US: AWS North Virginia
-     **Mendix Cloud US: AWS Oregon**

**Comment by udh-mendix** [comment]
@MarkvanMents good point, here are the details for the new clusters - 

Region | Start Time (UTC) | Local time | Estimated Duration
------------ | ------------- | ------------ | ------------- |
Singapore | 17:00 | 01:00 | 1 hour
Dublin | 23:00 | 22:00 |  1 hour
Oregon | 07:00 | 00:00 | 1 hour

**Comment by MarkvanMents** [comment]
Thanks
Let me know here (or via Slack) when you release the change and I'll publish.

**Comment by MarkvanMents** [comment]
Release Confirmed

**Pull request merged**
