### PR TITLE
Undocument the ReadCommittedSnapshot option

### PR DESCRIPTION
**Pull request by basdebakker**
We decided that we cannot support customers running with the ReadCommittedSnapshot option set to the non-default value of false, so it would be better to not mention the option in the documentation. This change has been approved by @arjenw .

### CODE REVIEW

**Comment by MarkvanMents** [comment]
Hi @basdebakker - looks OK.
Do we need to communicate this in a release note or to any SQL Server customers who may be using this setting? @NielsTrots - do you have a view on this from the support perspective. Is the number of customers who might be affected so small we don't need to bother doing anything else?

**Comment by basdebakker** [comment]
Note that the option remains in the code, so people using it will not be affected directly.

**Comment by MarkvanMents** [comment]
OK - I'll publish this and update it later if I get further feedback.
Thanks @basdebakker

**Review by MarkvanMents — APPROVED** [review]
Change approved.
Change also reflected in Mendix 9 documentation.

**Pull request merged**
