### PR TITLE
Add switch (web) 3.0.0 documentation

### PR DESCRIPTION
**Pull request by jordanch**
The soon-to-be-released Switch widget is version 3.0.0. 

This PR updates the documentation for this widget under `Marketplace Guide` > `Widgets` section.

### CODE REVIEW

**Comment by jordanch** [comment]
Here's the [JIRA](https://mendix.atlassian.net/browse/WC-280) for releasing Switch 3.0.0

**Comment by jordanch** [comment]
Please do not merge until Switch is released. I have marked this WIP in the title until then.

**Review by Keraito — APPROVED** [review]
looks good from technical perspective

**Comment by jordanch** [comment]
@ConnorLand ready to merge.

**Review by ConnorLand — APPROVED** [review]

**Pull request merged**
