### PR TITLE
Resolve problems with Menu Build - incorrect backward (parent) refere…

### PR DESCRIPTION
**Pull request by MarkvanMents**
…nces:

@Adam-Dupaski, can you just check that this is what was needed to resolve the menu-building problems that Travis was reporting.
I've done a PR just in case this isn't what was intended.

`[12:07:42] [MENU_BUILD] File /refguide/charts-advanced-cheat-sheet.md has parent Chart Widgets which would resolve to /refguide/Chart Widgets, but this does not exist
[12:07:42] [MENU_BUILD] File /refguide/charts-any-building-bocks.md has parent Chart Widgets which would resolve to /refguide/Chart Widgets, but this does not exist
[12:07:42] [MENU_BUILD] File /refguide/charts-any-cheat-sheet.md has parent Chart Widgets which would resolve to /refguide/Chart Widgets, but this does not exist
[12:07:42] [MENU_BUILD] File /refguide/charts-any-configuration.md has parent Chart Widgets which would resolve to /refguide/Chart Widgets, but this does not exist
[12:07:42] [MENU_BUILD] File /refguide/charts-configuration.md has parent Chart Widgets which would resolve to /refguide/Chart Widgets, but this does not exist
[12:07:43] [MENU_BUILD] File /refguide/ui-resources-package.md has category Modeler which has no file associated to it or is not used in spaces.yml`

### CODE REVIEW

**Comment by MarkvanMents** [comment]
@Adam-Dupaski 

I've solved the breaking travis build. There are still warnings, but I think these will go if we merge to development.

Can you check that this is actually what was wanted, just in case there was a reason for having it different?

Thanks

**Comment by Adam-Dupaski** [comment]
@MarkvanMents I thought I already fixed all the warnings, actually. Everything's built. This link works - `[Charts reference guide](../../refguide/charts-widgets)`: https://docs.mendix.com/howto/extensibility/charts-theme#4-reference

**Comment by Adam-Dupaski** [comment]
@MarkvanMents Travis fix: https://travis-ci.org/mendix/docs/builds/399537780

**Comment by Adam-Dupaski** [comment]
@MarkvanMents Take in mind this was a merge effort on the PR that was assigned to me, not a proofreading effort. So I didn't proofread any content or filenames - I just got the PR merged and built. We have to coordinate better about what needs to attention for fixing and verifying, because this is just extra work on a build that already functions okay. It's the proofreading that really needs to be done.

**Comment by MarkvanMents** [comment]
@Adam-Dupaski 

There are no child documents for Chart Widgets
The Chart Widget markdown file does not match the title

The links in section 3.1 of Chart Widgets go to pages with no corresponding menu entry.

That should be resolved by this PR

**Comment by MarkvanMents** [comment]
Not proofreading... I haven't changed (or read) any of the text

**Comment by MarkvanMents** [comment]
Travis fix: https://travis-ci.org/mendix/docs/builds/399537780

Lines 515 to 520 are what I looked at because I was getting the same warnings on my builds.

**Comment by MarkvanMents** [comment]
I think that it was because the issues were with the menu build and not the links inside the documents. The warnings appeared somewhere else.

But strange you've never seen it before!

**Comment by Adam-Dupaski** [comment]
Yeah, I guess the `parent` metadata doesn't throw an error/warning, and I always verify the sidebar after the build anyway. So I need to pay better attention to that part of the build log. ;)

**Comment by MarkvanMents** [comment]
This is where the system is very delicate.
None of those documents have file titles which match the file names!!
I would say that this shouldn't break anything - but I think that in this case it does.
I thought that the rename to chart-widgets.md would solve the problem as the parent metadata is now correct in the child documents. But there is more to it than that.

**Comment by Adam-Dupaski** [comment]
@MarkvanMents Yes, I'll verify this all tomorrow, don't have any more time tomorrow. Thanks for your help.

**Comment by MarkvanMents** [comment]
@Adam Dupaski<mailto:Adam.Dupaski@mendix.com> Your welcome. Sorry my PR wasn’t sufficient to solve the problem entirely.

**Comment by Adam-Dupaski** [comment]
@MarkvanMents Looks like the Charts Widget section is okay now:

https://documentation-accp.cfapps.io/refguide/chart-widgets

But I'll verify everything again tomorrow. This was the PR: https://github.com/mendix/docs/pull/1237/files

126 files is way too big for one PR!

Cheers.

**Pull request merged**
