### PR TITLE
8.16 Release Data Hub and Integration changes 

### PR DESCRIPTION
**Pull request by ilagordhan**
Merged #2835 and further file changes

### CODE REVIEW

**Comment by ilagordhan** [comment]
@Adam-Dupaski I have asked @MarkvanMents to approve this merge request of all combined 8.16 changes and merge it tomorrow. There is one check which is the reference to the 8.16 release note which is not published.
Is that OK with you?

**Comment by Adam-Dupaski** [comment]
@ilagordhan Yes, ofc good to plan in advance for someone to merge as you'll be PTO, but why does Mark have to approve - are you also requesting review?

Keep in mind that 8.16 RN will be published first, so you can add the link to the RN, because this PR will be merged after and the link will work.

**Comment by ilagordhan** [comment]
@Adam-Dupaski I have not found out how to mark that it does not require review. Do you have a suggestion please?

**Comment by Adam-Dupaski** [comment]
If it's your PR and you have admin rights (which we all do on the team), then no review/approval is necessary. So Mark can merge this without having to approve it.

**Comment by MarkvanMents** [comment]
Hi @ilagordhan, you can add me as an assignee rather than a reviewer. You can assign up to 10 people.
I've done that and also removed the WIP label as I think it is ready to go when 8.16 is published?

**Comment by ilagordhan** [comment]
Brilliant Mark, I did not know about multiple assignee and was puzzling the the review construct. Thanks for taking care of it Mark.

**Review by MarkvanMents — APPROVED** [review]
Will now merge

**Comment by MarkvanMents** [comment]
All commits cherry picked to mx9-docs
https://github.com/mendix/mx9-docs/commit/da50b0320e41a62e89a2f31d75e176c4f6d7016e

**Pull request merged**
