### PR TITLE
Move cloud docs

### PR DESCRIPTION
**Pull request by JelteMX**
Request per @katamaks and @jtwaleson to move these docs

### CODE REVIEW

**Comment by jtwaleson** [comment]
I think the two Amazon/Azure files are now missing

**Comment by JelteMX** [comment]
@jtwaleson Nope, they are duplicated:

https://docs.mendix.com/deployment/aws/how-to-deploy-a-mendix-app-on-amazon-web-services
https://docs.mendix.com/deployment/azure/how-to-deploy-a-mendix-app-on-azure

So I am removing the ones from mendixcloud and redirect those to the two mentioned above

**Comment by JelteMX** [comment]
These ones will be removed (and redirected)

https://docs.mendix.com/deployment/mendixcloud/how-to-deploy-a-mendix-app-on-amazon-web-services
https://docs.mendix.com/deployment/mendixcloud/how-to-deploy-a-mendix-app-on-azure

**Comment by jtwaleson** [comment]
Oh, ok, good :)

**Pull request merged**
