### PR TITLE
Backport Add new runtime setting UseMimeDecoderForBase64 to 9.6.10

### PR DESCRIPTION
**Pull request by fazzdev**
Backport of changes which are documented for 9.12.0
This is dependent on changes made in #4220 and assumes that 9.12.0 is released before 9..6.10

### CODE REVIEW

**Comment by fazzdev** [comment]
Please merge https://github.com/mendix/docs/pull/4220/files first!

**Review by MarkvanMents — APPROVED** [review]
Thanks @fazzdev

**Comment by Adam-Dupaski** [comment]
9.6.10 was released yesterday, so this needs to be published ASAP.

**Comment by MarkvanMents** [comment]
Closing this in favor of #4297

**Pull request closed without merging**
