### PR TITLE
AAT document changes

### PR DESCRIPTION
**Pull request by Karuna-Mendix**
https://mendix.atlassian.net/browse/TW-2311

### CODE REVIEW

**Comment by Karuna-Mendix** [comment]
Hi @MXClyde, could you please review the PR and approve it?

**Review by MXClyde — CHANGES_REQUESTED** [review]
Thanks for your patience. Looks good to me! Some remarks:

- Typo in line 14:  Kafka is used for long-term immutable data storage **of** audit..
- Line 24 we need to be a bit more tentative (i.e. not suggest that implementing AAT will suddenly make you compliant). E.g: "Tracks changes to data (who made what changes, at what time, and in what context) to help you develop apps that are GxP and FDA CFR 21 Part 11 compliant"
- Line 25: "without requiring any changes to domain models". This is not true. I would remove this last part of the sentence.
- Line 30: "the old value and the new value" sounds better than "old value and the changed value", right?
- Line 58: "that comes with a subscription fee"
- Line 89: are you sure about the OAuth authentication? I believe/expect this is only for Admin role

**Comment by Karuna-Mendix** [comment]
Hi @MXClyde, I reviewed all feedback comments except for line 89. Do you mean to move OAuth authentication from **_AddOn_CanChangeEnvironmentInQuery:** to **Admin** role? I edited the content as per this [draft document](https://mendix.atlassian.net/wiki/spaces/idx/pages/2666660012/AAT+External+Documentation#3.1-Configuring-Module-Roles):

**Comment by MXClyde** [comment]
> Hi @MXClyde, I reviewed all feedback comments except for line 89. Do you mean to move OAuth authentication from **_AddOn_CanChangeEnvironmentInQuery:** to **Admin** role? I edited the content as per this [draft document](https://mendix.atlassian.net/wiki/spaces/idx/pages/2666660012/AAT+External+Documentation#3.1-Configuring-Module-Roles):

Yes, I believe having it only under Admin would be correct, but IDX team should be able to verify and confirm

**Comment by Mallikarjun3637** [comment]
@Karuna-Mendix Its good to have in Admin

**Pull request merged**
