### PR TITLE
Add remark about placing tags

### PR DESCRIPTION
**Pull request by feddovanede**
See https://mendixsupport.zendesk.com/agent/tickets/129382

### CODE REVIEW

**Comment by feddovanede** [comment]
Should we add (a link to) the schema for pluggable widgets to make it more clear where tags should be placed?

**Comment by MarkvanMents** [comment]
@ConnorLand - is this PR for you?

**Comment by ConnorLand** [comment]
Yes I'll take it thanks @MarkvanMents

**Review by ConnorLand — APPROVED** [review]

**Comment by ConnorLand** [comment]
Thanks @feddovanede . The widget how-to's are complex, so this is a welcome PR stemming from real user experience. Thanks.

**Pull request merged**
