### PR TITLE
Add multiple constraint known issue to Mendix 8 GA

### PR DESCRIPTION
**Pull request by ishan1729**

### CODE REVIEW

**Comment by ishan1729** [comment]
This pull request needs an internal RnD review first.

**Comment by passalaqua** [comment]
I think I like this wording a little better:

> We return incorrect results for XPath queries when the same entity member (either an attribute or an association) is compared against different values.

What do you think?

**Comment by Adam-Dupaski** [comment]
@ishan1729 which SDM verified this public known issue?

**Comment by ishan1729** [comment]
> We return incorrect results for XPath queries when the same entity member (either an attribute or an association) is compared against different values.

Looks good to me. I will apply this suggestion.

**Comment by Adam-Dupaski** [comment]
@ishan1729 is your review done and is this ready to be published?

**Comment by passalaqua** [comment]
> @ishan1729 is your review done and is this ready to be published?

I reviewed it. We're ready to publish.

**Pull request merged**
