### PR TITLE
Ats2 releasenotes donotpublishbefore19/10/2017

### PR DESCRIPTION
**Pull request by zwartd**

### CODE REVIEW

**Comment by Adam-Dupaski** [comment]
Email Arjan when reviewed.

**Comment by zwartd** [comment]
The release of ATS 2.0 is postponed. There is no definitief new date yet.

**Comment by zwartd** [comment]
Hi @Adam-Dupaski,

The release notes may be published. I will update the other PR's with the latest docs and then add a comment if they may be published. If you have questions don't hesitate to ask!

**Comment by Adam-Dupaski** [comment]
@zwartd In release-notes-2.md, you wrote: "We've extended ATS with a new simple API. Via this API, you can run your automated tests from any external tool. A good option for such a tool is Jenkins. We've documented how to set up Jenkins with ATS in a [How-to](/ats/howtos/)." What specific how-to is this? It should be linked.

**Comment by zwartd** [comment]
Hi @Adam-Dupaski,

It is the "ats-and-ci-cd-2" how-to which is currently in PR 795. Can I just add the links? (Since it will break the build.)

**Comment by Adam-Dupaski** [comment]
@zwartd Please make a note to add links to that how-to as well as to Reference Guide 2 once those are published. I cannot merge PR 795 yet, as it needs a thorough review (based on a quick look, I see several types of unnecessary changes). I will merge this PR now.

**Pull request merged**
