### PR TITLE
Ctrl-Alt-G does not work (anymore)

### PR DESCRIPTION
**Pull request by TimvanSteenbergen**
Ctrl-Alt-G does not work (anymore), but I do not know what the alternative is. Maybe any of you do?

### CODE REVIEW

**Comment by Adam-Dupaski** [comment]
Hi @TimvanSteenbergen, this is not an issue that can be resolved by adding this note to the doc. This needs testing and potential bug resolution. Can you send a Support request for this?: https://support.mendix.com/hc/en-us

**Comment by Adam-Dupaski** [comment]
Hi @TimvanSteenbergen can you send a Support request for this? This needs to be verified in the product, not the docs.

**Comment by Adam-Dupaski** [comment]
@TimvanSteenbergen Trying to verify this. Are you using a Mac?

**Comment by Adam-Dupaski** [comment]
@TimvanSteenbergen Or Linux?

**Comment by TimvanSteenbergen** [comment]
I'dd rather not talk about that amongst programmers, but I am on "Windows 10 Home".

**Comment by Adam-Dupaski** [comment]
@TimvanSteenbergen I created a Support request for this, it will be investigated, the doc will be updated if necessary.

**Pull request closed without merging**
