### PR TITLE
New database alerts

### PR DESCRIPTION
**Pull request by matyaskuti**
Documentation for new database alerts: freeable memory, database IOPS burst balance.
Related Jira ticket: DVAS-1102

### CODE REVIEW

**Comment by matyaskuti** [comment]
@MarkvanMents @tomedegroot could you please review?

**Comment by MarkvanMents** [comment]
Hi @matyaskuti do you have an estimated release date for this - it's useful to add it to the description so I have all the information in one place.
Doesn't matter if it is only an estimate.

**Comment by matyaskuti** [comment]
@MarkvanMents regarding the release date, it is entirely at our own discretion at the moment. Thus if the documentation is approved, we can release this and the new alerts at the exact same time.

**Comment by MarkvanMents** [comment]
Hi @matyaskuti 
The language looks OK.
Can you add a release note for the customer too. You can leave a placeholder for the date.
Let me know when you release it, and I can publish.

**Comment by matyaskuti** [comment]
@MarkvanMents release notes updated with tomorrow's date, for now.

**Pull request merged**
