### PR TITLE
Database alerts section updated

### PR DESCRIPTION
**Pull request by denis-shuvalov**
'Application Server Memory' alert is removed,
Critical threshold for 'Database Freeable Memory' is changed to 10%.

### CODE REVIEW

**Review by udh-mendix — APPROVED** [review]
We're cleaning up the alerts page by deleting obsolete alerts that don't work (Application server memory) and by fixing and enabling a broken alert with new thresholds (Database freeable memory)

**Comment by MarkvanMents** [comment]
Hi Kasia @katarzyna-koltun-mx 
You worked on the alerting before, do you want to pick this up and liaise with Denis (@denis-shuvalov ) and Umang (@udh-mendix ) on the release date.

Denis has asked for a release note - but it might be easier to do this in a separate Pull Request unless Denis gives you write access to his fork of Mendix docs.

Let me know if you have any questions.

**Comment by katarzyna-koltun-mx** [comment]
@denis-shuvalov I've checked the update, nothing to correct on my end. I'm going to merge it on Monday as discussed.

Regarding the release note, I will open a separate PR, unless you want to write it as well?

**Comment by katarzyna-koltun-mx** [comment]
Release note: https://github.com/mendix/docs/pull/5175

**Comment by katarzyna-koltun-mx** [comment]
Merging per agreement with @denis-shuvalov and @udh-mendix

**Pull request merged**
