### PR TITLE
Update 9.5.0 release notes with known issue

### PR DESCRIPTION
**Pull request by jveldhuizen**

### CODE REVIEW

**Comment by MarkvanMents** [comment]
Hi Jonathan, @jveldhuizen 
Since this is a known issue in 9.5 should this be published immediately?
I'll need to take out the fix information and add it later.
Do you have a zendesk ticket or JIRA KNOWN_PUBLIC_ISSUE for this?
Let me know what you want to do with this - I'll mark it for 9.6 for now until I know what the best solution is.
Mark

**Comment by jveldhuizen** [comment]
Hi @MarkvanMents , preferable, we add this as soon as possible to the 9.5 release notes. The Jira issue is RTI-308, the currently known ticket numbers 129493, 129605 and 129902.

**Comment by MarkvanMents** [comment]
OK - I"ll remove the fix information and publish now.

**Comment by jveldhuizen** [comment]
Thanks!

**Pull request merged**
