### PR TITLE
Update basic-package.md

### PR DESCRIPTION
**Pull request by TimvanSteenbergen**
Apparently no documentation exists yet on deploying the app for a Basic package, see https://forum.mendix.com/link/questions/112701. So I created it, hope you like it.

### CODE REVIEW

**Comment by MarkvanMents** [comment]
Hi @TimvanSteenbergen 
These instructions are already linked from [Migrate a Free App to Mendix Basic](https://docs.mendix.com/developerportal/deploy/migrate-free-app-to-basic#3-6-deploy-your-app), where section 3.6 links to the same set of instructions in the [Mendix Cloud - deploy](https://docs.mendix.com/developerportal/deploy/mendix-cloud-deploy#3-deploying-a-licensed-app-to-the-mendix-cloud) documentation.

I don't really want to duplicate the same set of instructions in multiple places if I can help it. Do you think that a link to that section of the Mendix Cloud deploy might be a good alternative?

**Comment by TimvanSteenbergen** [comment]
Crap, I have overlooked that doc and link. Could have saved me some time there, by better rtfm-ing. Totally agree: no duplicate content. So: yes a link will do.

**Comment by MarkvanMents** [comment]
Thanks for picking up the question on the forum and responding positively by helping with documenting the solution. Sorry that you ended up having to do more work in this case.

I'll use this PR to make the link to the existing documentation stand out more, as that was obviously a weakness in this case.

**Review by MarkvanMents — APPROVED** [review]
Thanks for the submission Tim.

**Pull request merged**
