### PR TITLE
Update warning suppression screenshots to match Studio Pro 8.8

### PR DESCRIPTION
**Pull request by mrseanryan**
Update the warning suppression screenshots to match Studio Pro 8.8

### CODE REVIEW

**Comment by paulmendix** [comment]
@MariaShaposhnikova This pr also needs some small textual changes, the table at https://docs.mendix.com/refguide/suppression-rules#rule-settings should say `Suppress for` and not `Warning selector`, and the reference to `Add Suppression dialog` should be `Add Suppression Rule dialog`, and the `Edit Suppression dialog` should be `Edit Suppression Rule dialog`.

**Comment by mrseanryan** [comment]
@paulmendix  @MariaShaposhnikova  I processed those comments - thank you

Sean

**Comment by mrseanryan** [comment]
@MariaShaposhnikova  thanks for approving.
I do not have permissions to merge - so I guess you can do that next ?

Regards
Sean

**Comment by MariaShaposhnikova** [comment]
@mrseanryan , I will merge it when 8.8 is released.

**Pull request merged**
