### PR TITLE
TLS/SSL improvements for Mendix Cloud v4

### PR DESCRIPTION
**Pull request by Infra-Red**
Signed-off-by: Andrei Krasnitski <andrei.krasnitski@mendix.com>

### CODE REVIEW

**Comment by MarkvanMents** [comment]
@Infra-Red 
Hi Andrei,
Did this get released? Sorry about the delay in publishing the release notes, I've been in meetings the last two days and didn't realise this was urgent - feel free to remind be if things are urgent!

**Comment by MarkvanMents** [comment]
Converted to draft = GitHub WIP to clarify status in list of PRs.

**Comment by Infra-Red** [comment]
Hi @MarkvanMents, the PR is ready for review.

**Review by MarkvanMents — APPROVED** [review]
@Infra-Red 
Looks good - can I publish it?

**Comment by MarkvanMents** [comment]
According to Andrei in Slack, this change is now live. So publishing.

**Pull request merged**
