### PR TITLE
Update publish-rest-service.md

### PR DESCRIPTION
**Pull request by norricorp**
See https://forum.mendix.com/link/questions/116164

### CODE REVIEW

**Comment by norricorp** [comment]
I have no idea what this means

**Comment by johannahemminger** [comment]
Hi @norricorp , thanks very much for your contribution! I will look into this and make the necessary changes. Would you mind signing the Contributor License Agreement linked in the CLAassistant comment above? It takes a few minutes to load, but then it's just ticking the box at the bottom. It's something we require from all our contributors.

**Comment by norricorp** [comment]
Hi Johanna,
CLA signed. I assume this means that Siemens now have the property rights to my home and any other assets?

**Comment by johannahemminger** [comment]
Not Siemens, they're all mine!! ;) Thanks very much for your contribution, will merge now.

**Comment by norricorp** [comment]
Where would you like me to leave the keys?

**Pull request merged**
