### PR TITLE
Update Quickstart Guides

### PR DESCRIPTION
**Pull request by ConnorLand**
Updating the quickstart guides (mostly screenshot changes)

### CODE REVIEW

**Comment by Adam-Dupaski** [comment]
@ConnorLand doing some edits here to accommodate new Hello World quickstart and language reviews: https://github.com/mendix/docs/pull/6882 - shouldn't interfere with screenshot updates

**Comment by Adam-Dupaski** [comment]
@ConnorLand part 1 PR merged; part 2 review started: https://github.com/mendix/docs/pull/6889

**Comment by Adam-Dupaski** [comment]
I looked at fixing these conflicts, but it will be better if you do it while knowing the new screenshots and image file names you want to use. Please let me know if you have questions on my content edits.

**Comment by ConnorLand** [comment]
> I looked at fixing these conflicts, but it will be better if you do it while knowing the new screenshots and image file names you want to use. Please let me know if you have questions on my content edits.

I am going to resolve conflicts in this PR and then merge so that all the screenshots are updated. Ryan also has some text updates he wants to make to both docs in the next few days. Therefore, please ping me when you're ready to merge https://github.com/mendix/docs/pull/6889/ next week so I can coordinate Ryan's updates after yours merges.

**Comment by Adam-Dupaski** [comment]
@ConnorLand thanks will do, https://github.com/mendix/docs/pull/6889 is almost ready to go, I'll probably merge Monday

**Pull request merged**
