### PR TITLE
Add conversion table for CAST

### PR DESCRIPTION
**Pull request by dahfjkg**

### CODE REVIEW

**Comment by Adam-Dupaski** [comment]
@dahfjkg do you work for Mendix?

**Comment by dahfjkg** [comment]
> @dahfjkg do you work for Mendix?

yes :)

**Comment by Adam-Dupaski** [comment]
@dahfjkg identifying yourself as a Mendix employee is necessary for GitHub

**Comment by Adam-Dupaski** [comment]
@dahfjkg Please sign the [CLA](https://www.clahub.com/agreements/mendix/docs).

**Pull request merged**
