### PR TITLE
Add a 'Signing In' section to the installation page of the Studio Pro refguide

### PR DESCRIPTION
**Pull request by joerih**
And describe how to handle the 'Untrusted Certificate' dialog that may appear.  

Add this to the refguide for both the Mendix 10 and Mendix 9 versions.

### CODE REVIEW

**Comment by joerih** [comment]
@Yiyun333 Did I just accidentally remove a commit with styling changes you did? I updated the screenshots in my branch, but I was not aware this would immediately change the content of the pull request.

@joerih Haha, indeed, my commit was removed just now. I thought something wrong with GitHub. But no worries, if you are ready now, I will do my review again.

**Comment by Yiyun333** [comment]
@joerih I see that you just did some more recent update to this PR. Please let me know when this PR is ready for language review. I will start my review when your update is finalised. Thanks!

**Comment by joerih** [comment]
@Yiyun333 Yes, my apologies, I just wanted to update the screenshots and I realized too late that I failed to keep your commit with that change.

However, I managed to restore your commit from the git history. Could you please check if it's alright?

Also, I don't intend to do any more updates, so you can take it from here.

**Comment by Yiyun333** [comment]
> @Yiyun333 Yes, my apologies, I just wanted to update the screenshots and I realized too late that I failed to keep your commit with that change.
> 
> However, I managed to restore your commit from the git history. Could you please check if it's alright?
> 
> Also, I don't intend to do any more updates, so you can take it from here.

@joerih No worries. Thanks for bringing my commit back. The PR looks good! I will merge it soon then ;)

**Pull request merged**
