### PR TITLE
[APPEXT-563] Add the untyped model api docs

### PR DESCRIPTION
**Pull request by pavel-constantinov**

### CODE REVIEW

**Comment by MarkvanMents** [comment]
@pavel-constantinov - is this for release now, or is it a new feature in 10.15?

**Comment by pavel-constantinov** [comment]
As far as I know it is planned to be released as soon as possible because it got delayed by quite a while.

**Comment by bvanreeven** [comment]
@MarkvanMents This is a new feature that will be released in 10.15 (provided we make the freeze in two weeks 😉).

**Comment by Luyao-Zhang-1** [comment]
@pavel-constantinov I edited the files. Could you please review the changes when you have time?

**Comment by pavel-constantinov** [comment]
> @pavel-constantinov I edited the files. Could you please review the changes when you have time?

Hi @Luyao-Zhang-1, I also posted a few changes just now, please take a look, I hope you'd agree that I improved the wording. If you have any other ideas, I'd be happy to see them!

**Comment by pavel-constantinov** [comment]
Rebased to get rid of the conflict blocking the merge.

**Review by Luyao-Zhang-1 — APPROVED** [review]

**Pull request merged**
