### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by hansthen**

### CODE REVIEW

**Comment by MarkvanMents** [comment]
@hansthen - I'm afraid I don't understand this release note at all.

Did you release a new version of something - if so what.  If it was a new release, did it potentially solve the problem for other users as well? I think that the amount of information here is just going to worry the users that new software is going out with specific code for a specific customer.

**Comment by Adam-Dupaski** [comment]
@hansthen Yes, we need more specific details here, otherwise there is no reason to publish such a release note. Release notes should detail the issue/fix, but they do not need to specify whether something was fixed for a specific customer. This is already over a week old - can we update or should we close the PR? Thanks.

**Comment by hansthen** [comment]
Yes please close.

**Comment by MarkvanMents** [comment]
@hansthen Thanks for the confirmation. Will close this PR.

**Pull request closed without merging**
