### PR TITLE
Release notes for Catalog 2.81

### PR DESCRIPTION
**Pull request by sjoerdbreur**
To be released tomorrow morning (1-6)

### CODE REVIEW

**Comment by MarkvanMents** [comment]
@johannahemminger is off today, so I've asked @katarzyna-koltun-mx to review. Please let us know here, or in the docs channel in Slack when the release is successful.
Thanks.

**Comment by katarzyna-koltun-mx** [comment]
@sjoerdbreur I've reviewed the file. Ready to publish on 1/6 after you give the go ahead.

**Comment by sjoerdbreur** [comment]
@katarzyna-koltun-mx Thank you! Added note to inform you after the release tomorrow.

**Review by katarzyna-koltun-mx — APPROVED** [review]

**Comment by johannahemminger** [comment]
Thanks @MarkvanMents @katarzyna-koltun-mx for taking care of this while I was out!

**Pull request merged**
