### PR TITLE
Add PUT method to the docs

### PR DESCRIPTION
**Pull request by HarishShankerAS**

### CODE REVIEW

**Comment by HarishShankerAS** [comment]
@quinntracy This is the documentation changes for PUT support in Consumed REST Service. This needs to be merged for 10.8 release. Please review when you have some time and let me know for any comments. Thanks in advance.

**Comment by quinntracy** [comment]
@HarishShankerAS I've reviewed the content and don't have any questions. I'll approve the PR for now, so just let me know if you have additional content you want to add prior to the release. Thanks!

**Review by quinntracy — APPROVED** [review]
Approved - notify for additional changes prior to 10.8 release

**Comment by HarishShankerAS** [comment]
@quinntracy Thanks for the approval, will you be merging it as well?

**Comment by HarishShankerAS** [comment]
@quinntracy Thanks for the approval, will you be merging it as well?

**Comment by quinntracy** [comment]
> @quinntracy Thanks for the approval, will you be merging it as well?

Yes, I have it covered :)

**Pull request merged**
