### PR TITLE
Added information on M2EE password. Made it clear how authorization is handled

### PR DESCRIPTION
**Pull request by gajduk**
Personally I had trouble following the guide with the information that is in right now. I think the following extention will make it more precise how the POST reqeusts need to be formated.

### CODE REVIEW

**Comment by Adam-Dupaski** [comment]
Hi Andrej,
Please take a minute to the sign the [CLA](www.clahub.com/agreements/mendix/docs).
Thanks.

**Comment by gajduk** [comment]
SIgned the CLA

**Comment by gajduk** [comment]
@Adam-Dupaski Signed the CLA

**Comment by Adam-Dupaski** [comment]
Merge via command line or manually to resolve conflicts.

**Comment by Adam-Dupaski** [comment]
Hi Andrej,
Thanks for your documentation PR. I am still trying to get this verified internally. Hoping that will be done soon and will let you know.
Cheers,
Adam

**Comment by Adam-Dupaski** [comment]
Verified by Jouke. Able to merge.

**Comment by Adam-Dupaski** [comment]
Andrej, I merged your changes manually. There's a merge conflict in this PR due to recent migration work we've been doing on the documentation. I will close this PR, but your changes have been merged and will be published, and you will be getting Mendix documentation points.
Thanks for the contribution!
Best,
Adam

**Pull request closed without merging**
