### PR TITLE
add docs for Viewer configurations

### PR DESCRIPTION
**Pull request by DISW-Mendix-3DViewer**

### CODE REVIEW

**Comment by DISW-Mendix-3DViewer** [comment]
@MarkvanMents please help review and merge.

**Comment by MarkvanMents** [comment]
Thanks for fixing the error @digital-engineering-services-sample-app 
Could you allow me to push changes to this PR, that would make things go quicker.
image

**Comment by MarkvanMents** [comment]
Closing this in favour of #5633 so that I can edit the files.

**Comment by DISW-Mendix-3DViewer** [comment]
> Thanks for fixing the error @digital-engineering-services-sample-app Could you allow me to push changes to this PR, that would make things go quicker. image

Thanks for the quick action, please go ahead!

**Pull request closed without merging**
