### PR TITLE
Ats2 referenceguide 2 donotpublishbefore19/10/2017

### PR DESCRIPTION
**Pull request by zwartd**
I created a separate commit for each file. I know the standard is creating a branch but it seemed to much to create so many branches.

### CODE REVIEW

**Comment by Adam-Dupaski** [comment]
After publishing, check formatting build of supported-widgets.md.

**Comment by zwartd** [comment]
The release of ATS 2.0 is postponed. There is no definitief new date yet.

**Comment by zwartd** [comment]
Hi @Adam-Dupaski, 

This PR may also be published.

**Comment by zwartd** [comment]
Hi @Adam-Dupaski,

I fixed all the links.

**Pull request merged**
