### PR TITLE
SAP Release Notes Week Ending 18 November

### PR DESCRIPTION
**Pull request by MarkvanMents**

### CODE REVIEW

**Comment by MarkvanMents** [comment]
Two questions:
1. Are there changes to the flow in https://docs.mendix.com/developerportal/deploy/sap-cloud-platform/#NewEnvironment which need to be documented, or is the new step clear?
2. Should I include a documentation change [here](https://docs.mendix.com/developerportal/deploy/sap-cloud-platform/#general-tab) for https://mendix.atlassian.net/browse/MCDEP-1170 since the UUID will now be visible to the customer?

**Comment by gauravkrshah** [comment]
> Two questions:
> 
> 1. Are there changes to the flow in https://docs.mendix.com/developerportal/deploy/sap-cloud-platform/#NewEnvironment which need to be documented, or is the new step clear?
[Gaurav]: There will not be any change in New Environment creation flow. Like PostgreSQL, once Hana database service is selected. 
> 2. Should I include a documentation change [here](https://docs.mendix.com/developerportal/deploy/sap-cloud-platform/#general-tab) for https://mendix.atlassian.net/browse/MCDEP-1170 since the UUID will now be visible to the customer?



> Two questions:
> 
> 1. Are there changes to the flow in https://docs.mendix.com/developerportal/deploy/sap-cloud-platform/#NewEnvironment which need to be documented, or is the new step clear?
[Gaurav]: An updated screenshot need to be added in Hana database section like we have for Postgres to show from where to upload configuration. https://docs.mendix.com/developerportal/deploy/sap-cloud-platform/#sap-hana . 
> 2. Should I include a documentation change [here](https://docs.mendix.com/developerportal/deploy/sap-cloud-platform/#general-tab) for https://mendix.atlassian.net/browse/MCDEP-1170 since the UUID will now be visible to the customer?
[Gaurav]: Not required. Rather we should update screenshot to show option of Mendix studio target.

**Review by gauravkrshah — APPROVED** [review]
Looks Good. Thanks!

**Comment by MarkvanMents** [comment]
Release approved over Slack

**Pull request merged**
