### PR TITLE
Deployment Release Notes 5 November 2020

### PR DESCRIPTION
**Pull request by MarkvanMents**

### CODE REVIEW

**Comment by mbyregowMx** [comment]
Can we change the last point in release notes to "We resolved an issue where sometime incorrect debugger password was shown for cloud v4 apps in developer portal, due to which customers were not able to connect to the debugger"

**Comment by ManpreetRiar** [comment]
@MarkvanMents The Release is done, please go ahead to publish documentation.

**Comment by MarkvanMents** [comment]
@mbyregowMx I've made the change.
@ManpreetRiar Merging now.

**Comment by ConnorLand** [comment]
Looks good @MarkvanMents.

**Pull request merged**
