### PR TITLE
Update mendix-cloud.md

### PR DESCRIPTION
**Pull request by RCatersels**
I find it strange that an upgrade of Postgres is advised since the cloud is still on 9.6. So installing an higher version is imho ill advice. Updating PGAdmin also solves the issue and should be the perferred method.

### CODE REVIEW

**Comment by MarkvanMents** [comment]
@pommi 
Hi Pim,
This was your change. Do you agree that this is a good alternative to the original suggestion?

**Comment by pommi** [comment]
I get what @RCatersels is saying, but we advise to upgrade the PostgreSQL **client** software. PGAdmin can be seen as one, like all other PostgreSQL clients, mentioned on https://wiki.postgresql.org/wiki/PostgreSQL_Clients.

We could change the text a little bit by changing:
```
, for example PostgreSQL 12 or 13.
```
To:
```
, for example PostgreSQL client 12 or 13, pgAdmin 4.12+.
```

**Comment by MarkvanMents** [comment]
@pommi 
Does this look OK now, Pim?

**Comment by pommi** [comment]
Looks good to me :+1:

**Review by MarkvanMents — APPROVED** [review]
Thanks for the suggestion Ronald (@RCatersels)
The development team would like to keep the other options, so I've added your suggestion rather than replacing the existing ones.
Thanks for the submission and improving the Mendix documentation. Thanks for taking the trouble to provide a link as well, that is always helpful to our customers.
Yours
Mark

**Pull request merged**
