### PR TITLE
Add Runtime release notes for 6.10.6

### PR DESCRIPTION
**Pull request by lhohan**
(we forgot to add, sorry)

### CODE REVIEW

**Comment by Adam-Dupaski** [comment]
Hi Hans,
Please take a second to sign the [CLA](https://www.clahub.com/agreements/mendix/docs).
Thanks.

**Comment by lhohan** [comment]
Hi Adam,

You do realise I work for Mendix directly right?

Kind regards,

Hans

2017-05-16 9:30 GMT+02:00 Adam Dupaski <notifications@github.com>:

**Comment by JelteMX** [comment]
True, but CLAHub does not make that distinction. The CLA is irrelevant to Mendix employees, yet if you sign it, we don't get the warning in the PR that this person did not sign the CLA yet.

**Comment by Adam-Dupaski** [comment]
Yes.

**Pull request merged**
