### PR TITLE
SAP Release: Configurator update and unbinding SAP services

### PR DESCRIPTION
**Pull request by MarkvanMents**
Planned release 30 August

### CODE REVIEW

**Comment by RishikeshJaadhav9** [comment]
The image for the autoscaler service should have been different in [Heimdal](https://cdpv4-test.mendixcloud.com). It is now corrected. 
So [this](https://github.com/mendix/docs/blob/d79f824a1e48cdc714267f7d457927b9da77db65/content/developerportal/deploy/attachments/sap-cloud-platform/service-connect.png) image can be updated to the one attached.

autoscaler

**Comment by RishikeshJaadhav9** [comment]
[Image](https://docs.mendix.com/partners/sap/attachments/sap-postgresql-on-aws/database-new-app.png) can be updated to the one attached. This was a UI [bug](https://mendix.atlassian.net/browse/MCDEP-655) that has been fixed. 

create dev env page

**Comment by MarkvanMents** [comment]
Commit https://github.com/mendix/docs/pull/3592/commits/ed4db1ce86e46143e3d6da779a83d68e1529594b adds files https://github.com/mendix/docs/pull/3592#issuecomment-898501105 and https://github.com/mendix/docs/pull/3592#issuecomment-898427576

**Review by RishikeshJaadhav9 — APPROVED** [review]
Looks Good.

**Review by RishikeshJaadhav9 — APPROVED** [review]

**Review by gauravkrshah — APPROVED** [review]
Looks Good. Thanks!

**Comment by RishikeshJaadhav9** [comment]
Configurator button caption is changed from "Open Editor" to "Configurator" to match with the Services tab button.

The following images can be replaced with the attached ones:
1. [database-new-app.png](https://github.com/mendix/docs/blob/ed4db1ce86e46143e3d6da779a83d68e1529594b/content/partners/sap/attachments/sap-postgresql-on-aws/database-new-app.png)
2. [database-new-environment.png](https://github.com/mendix/docs/blob/ed4db1ce86e46143e3d6da779a83d68e1529594b/content/partners/sap/attachments/sap-postgresql-on-aws/database-new-environment.png)
3. [add-binding-configuration.png](https://github.com/mendix/docs/blob/ed4db1ce86e46143e3d6da779a83d68e1529594b/content/developerportal/deploy/attachments/sap-cloud-platform/add-binding-configuration.png)

**Comment by MarkvanMents** [comment]
> 
> 
> Configurator button caption is changed from "Open Editor" to "Configurator" to match with the Services tab button.
> 
> The following images can be replaced with the attached ones:
> 

Images added in commit: https://github.com/mendix/docs/pull/3592/commits/137b7724b1496a006740c29e778beee4fa2ad17a

**Pull request merged**
