### PR TITLE
Update DatabaseJdbcUrl/DatabaseUseSsl description

### PR DESCRIPTION
**Pull request by basdebakker**
I'll have this change reviewed by the DataStorage team.

### CODE REVIEW

**Comment by Adam-Dupaski** [comment]
@basdebakker is this PR a WIP for the review you need, or can it be merged now?

**Comment by basdebakker** [comment]
> @basdebakker is this PR a WIP for the review you need, or can it be merged now?

The former.

**Comment by Adam-Dupaski** [comment]
@basdebakker please insert "WIP" in the title to let me know in the future please.

**Comment by basdebakker** [comment]
This change has been approved by @ishan1729 . As far as the DataStorage team is concerned this is ready to merge.

**Pull request merged**
