### PR TITLE
Draft: Updated documenation for your Mendix Profile. Release date unknown yet.

### PR DESCRIPTION
**Pull request by jurretanjamx**
Updated the documentation to be more clear about your profile and rewrite so it fits the newly design. 
Updated images as well.

### CODE REVIEW

**Comment by jurretanjamx** [comment]
@maxvandop @AnnYe-Fluithaas @TugbaSariAktas please have a look

**Review by TugbaSariAktas — APPROVED** [review]
Looks good to me.

**Comment by Adam-Dupaski** [comment]
@jurretanjamx let me know when ready for review.

**Comment by TugbaSariAktas** [comment]
@Adam-Dupaski It is ready for your review. Thanks.

**Comment by Adam-Dupaski** [comment]
@TugbaSariAktas please remove the Draft state

**Comment by TugbaSariAktas** [comment]
I think only Jurre could undraft it and he is on holiday. Are you able to undraft it? @Adam-Dupaski

**Comment by Adam-Dupaski** [comment]
Yes, undrafted @TugbaSariAktas , review in progress 👍

**Review by Adam-Dupaski — APPROVED** [review]

**Comment by Adam-Dupaski** [comment]
Thanks @jurretanjamx and @TugbaSariAktas - review done and updates made. Release notes will be needed.

**Comment by AnnYe-Fluithaas** [comment]
Hi @Adam-Dupaski -- Release date for this is now planned for Sept 13th. I'll check what's up regarding the release notes.

**Comment by MarkvanMents** [comment]
> 
> 
> Hi @Adam-Dupaski -- Release date for this is now planned for Sept 13th. I'll check what's up regarding the release notes.

Hi @AnnYe-Fluithaas - Adam will be off on 13th, so could you liaise with me or the rest of the docs team either here or on Slack.

**Comment by Adam-Dupaski** [comment]
@MarkvanMents @AnnYe-Fluithaas Luyao can pick this up, have already discussed with her - CC @Luyao-Zhang-1

**Comment by Adam-Dupaski** [comment]
Will fix these conflicts.

**Comment by Adam-Dupaski** [comment]
Closing this PR to resolve conflicts via a new branch/PR - #3687

**Pull request closed without merging**
