### PR TITLE
Update migrating-your-mendix-database.md

### PR DESCRIPTION
**Pull request by sahilpathania7**
Use Developer Portal to upload the migrated, exported database backup to the Mendix cloud. This can be accessed using the Nodes page in the Developer Portal: select your app and click the **Backup** and use the **Upload Backup** button to upload your Database using the file chooser to select the exported database file from your local file system. This will stop and clear your existing environment. After the upload is done, stop the application. Select the uploaded backup and click on Restore Backup to restore the new Backup. Start the application.

### CODE REVIEW

**Comment by MarkvanMents** [comment]
Hi @sahilpathania7 
Could you sign the license/cla by clicking the **Details** link next to the license pending note.
Although it isn't so important for Mendix employees, as contributing to documentation is part of your job description, it stops us getting a warning on the build.
Thanks.

**Comment by sahilpathania7** [comment]
Hello Mark,

It’s done, sorry for the delay in the reply.

Mit Freundlichen Grüßen/ Warm Regards/ Met vriendelijke groet

SAHIL PATHANIA
Senior Consultant
T
+49 1759 31 96 21

BUILDING
SMART
SOLUTIONS

***@***.***
CLEVR

**Review by MarkvanMents — APPROVED** [review]
Thanks for the submission @sahilpathania7 
Can this be published immediately?

**Comment by MarkvanMents** [comment]
Checking with backups team for technical verification.

**Comment by MarkvanMents** [comment]
Have checked through the steps and confirmed the changes.
Thanks for the submission - it looks like this How-To was still using the instructions for the deprecated (V3) version of Mendix Cloud. Great that you spotted this and suggested an update. It all helps to make our Mendix documentation better.
I also took the opportunity to split up the steps to match the style of our other documents.
Am merging this now.

**Pull request merged**
