### PR TITLE
add more explanation on log levels tab private cloud

### PR DESCRIPTION
**Pull request by cstevandy**
Added a more detailed explanation on how to use log levels.

### CODE REVIEW

**Review by MarkvanMents — COMMENTED** [review]
@cstevandy 
Hi Christian,
Can you check my changes and let me know if it is OK to merge.
Thanks.

**Comment by cstevandy** [comment]
Hi @MarkvanMents, it looks good to me.

**Review by MarkvanMents — APPROVED** [review]
@cstevandy 
Thanks for the submission.
I'll publish it now as there doesn't seem to be a dependency on a release?
Mark

**Comment by cstevandy** [comment]
@MarkvanMents, yes no dependency. Thanks, Mark.

**Pull request merged**
