### PR TITLE
Update scheduled-events.md

### PR DESCRIPTION
**Pull request by MxClaudineMaas**
https://mendix.slack.com/archives/C3T260XGA/p1632231097158200

### CODE REVIEW

**Review by MarkvanMents — COMMENTED** [review]
Hi Claudine, @MxClaudineMaas 
Thanks for the Pull Request - I saw it in the Slack discussions.
I have given the information its own heading, as it didn't seem to be totally related to Long Running Events. I also added additional information I saw in the discussion.
Can you just check that it is still OK. Then I can approve and merge.
Thanks
Mark

**Comment by MxClaudineMaas** [comment]
Hi Mark, 

I would not mention that it is hard-coded; this means that it is hard-coded in our code (which is not something we want to let customers know ;). For customers it means that they just can not change it themselves in any way.

**Comment by MarkvanMents** [comment]
HI Claudine,
I've changed it to
> This limit cannot be overridden and is independent of how the app is scaled.

I think it is useful to say that it cannot be changed, so the customer doesn't ask support to change the limit for them.
Is this OK?

**Comment by MxClaudineMaas** [comment]
Yes good point :), that saves us some tickets indeed :P!

And yes, agreed, thank you.

**Review by MarkvanMents — APPROVED** [review]

**Pull request merged**
