### PR TITLE
Update stories-api.md

### PR DESCRIPTION
**Pull request by Luyao-Zhang-1**

### CODE REVIEW

**Comment by Luyao-Zhang-1** [comment]
@Adam-Dupaski it seems that on the current [Stories API page](https://docs.mendix.com/apidocs-mxsdk/apidocs/stories-api), the information about WSDL is not complete. I compared the text with the text on the [Projects API](https://docs.mendix.com/apidocs-mxsdk/apidocs/projects-api) page, and make some adjustments. Could you take a look at the change and approve it if you think it is good?

**Comment by Adam-Dupaski** [comment]
@Luyao-Zhang-1 best to verify this with Olaf or someone from that team - this is a technical issue as to whether that same web service is really necessary. After that, good to merge.

**Comment by loket4** [comment]
The changes Luyao proposes seem to be procedural and not technical. They look good to me.

**Comment by Luyao-Zhang-1** [comment]
@loket4 thank you for checking. 
@Adam-Dupaski then I will merge this PR.

**Pull request merged**
