### PR TITLE
Update Custom Domain Certificate image

### PR DESCRIPTION
**Pull request by MarkvanMents**

### CODE REVIEW

**Comment by MarkvanMents** [comment]
@feddovanede 
I have a feeling that someone forgot to tell me that this change had been released.
Are the buttons now square, and should I publish this small change 😀

**Comment by MarkvanMents** [comment]
OK, I've checked and it seems it doesn't look like either of them any more. So I'll upload the new one and merge this PR.
image

**Comment by feddovanede** [comment]
This is probably related to the migration of Cloud Portal from Mx7 to Mx8. This did include some (minor) styling updates. The buttons are still all in the same place, and they still do the same, they might look slightly different. That means that all images on https://docs.mendix.com/developerportal/deploy/environments-details/ are also outdated.

**Comment by MarkvanMents** [comment]
> This is probably related to the migration of Cloud Portal from Mx7 to Mx8. This did include some (minor) styling updates. The buttons are still all in the same place, and they still do the same, they might look slightly different. That means that all images on https://docs.mendix.com/developerportal/deploy/environments-details/ are also outdated.

@Feddo - I have a task to review a whole load of images, so I'll add all the "Cloud Portal" ones as well.

**Pull request merged**
