### PR TITLE
Remove the limitation of associated attributes in DB2 and SAP HANA since it's no longer applicable.

### PR DESCRIPTION
**Pull request by snajahi**
The once documented limitation regarding associated attributes in DB2 and SAP HANA  is no longer applicable. We therefore should remove the related section in the documentation.

### CODE REVIEW

**Comment by dahfjkg** [comment]
Passed team review

**Review by MarkvanMents — APPROVED** [review]
Thanks @snajahi 
Approving this ready for 9.8.0

**Comment by snajahi** [comment]
> Hi Pavel, So this change is for 9.8.0? - I'll put a label on it to make sure it isn't merged before! It sounds like we need to keep something in the doc for customers who are using other versions which are not LTS? Perhaps, rather than deleting the section we could add a banner which says
> 
> > This limitation has been removed in versions x.xx.xx and above
> 
> What do you think?

Hi @MarkvanMents, the changes were updated as suggested. They might also require a review by someone from the security team.

**Comment by MarkvanMents** [comment]
> 
> 
> > Hi Pavel, So this change is for 9.8.0? - I'll put a label on it to make sure it isn't merged before! It sounds like we need to keep something in the doc for customers who are using other versions which are not LTS? Perhaps, rather than deleting the section we could add a banner which says
> > > This limitation has been removed in versions x.xx.xx and above
> > 
> > 
> > What do you think?
> 
> Hi @MarkvanMents, the changes were updated as suggested. They might also require a review by someone from the security team.

Done

**Comment by MarkvanMents** [comment]
Revived in #3908

**Pull request closed without merging**
