### PR TITLE
Add next up section to how tos

### PR DESCRIPTION
**Pull request by zwartd**

### CODE REVIEW

**Comment by Adam-Dupaski** [comment]
Hi @zwartd, please sign the [CLA](https://www.clahub.com/agreements/mendix/docs), this is required for merging all pull requests.

**Comment by Adam-Dupaski** [comment]
Hi @zwartd and @myrthewalhout, please sign the [CLA ](https://www.clahub.com/agreements/mendix/docs) if you have not already, this is required for merging pull requests. Thanks.

**Comment by Adam-Dupaski** [comment]
Hi @zwartd and @myrthewalhout, when is this PR supposed to be merged and published? Because PRs 781, 788, 789, and 790 are still labeled as "Future release" and so still need to be merged - but there is an overlap with this PR (i.e., for ht-version-1.md, the changes are the same as in PR 795).

**Comment by Adam-Dupaski** [comment]
Hi @zwartd, can this PR be merged? It seems it will only be changes to ht-version-1 docs.

**Comment by zwartd** [comment]
Hi @Adam-Dupaski,
Yes, you can merge this PR.

**Pull request merged**
