### PR TITLE
Updated cloud resource plans

### PR DESCRIPTION
**Pull request by aniruddhagalgali-mendix**

### CODE REVIEW

**Review by MarkvanMents — APPROVED** [review]
Looks good.
Can it be merged straight away?

**Comment by MarkvanMents** [comment]
@aniruddhagalgali-mendix 
Tom also mentions updating this document: https://docs.mendix.com/developerportal/deploy/scale-environment#3-scaling-your-environment. But I can't see where we would need to mention XXXL containers.

**Comment by aniruddhagalgali-mendix** [comment]
@MarkvanMents I believe what Tom is talking about the changes to the scaling dialog and the 32 GB per container limit. I'd changed  https://docs.mendix.com/developerportal/deploy/scale-environment#3-scaling-your-environment in PR: https://github.com/mendix/docs/pull/3561, but @MariaShaposhnikova 
 moved the content it to https://docs.mendix.com/developerportal/deploy/environments-details#scaling. So the info is there, but in a different page.

**Comment by MarkvanMents** [comment]
XXXL pack is released, merging.

**Pull request merged**
