### PR TITLE
Deprecate app services

### PR DESCRIPTION
**Pull request by Adam-Dupaski**
Replaces #2963.

### CODE REVIEW

**Comment by Adam-Dupaski** [comment]
8.18.2 or later

**Comment by Adam-Dupaski** [comment]
@GulamY @joostverhoog are app services deprecated/removed from support for 8.18.2?

**Comment by joostverhoog** [comment]
After careful consideration, we ended up deciding that the level of support for app services (deprecated) will not change. So this pull request can be closed.

**Comment by Adam-Dupaski** [comment]
@MarkvanMents see above - app services remain deprecated in Mx8, so the Dev Portal page will stay for the foreseeable future.

**Pull request closed without merging**
