### PR TITLE
Update odata-representation.md

### PR DESCRIPTION
**Pull request by lightpeak**
Addition about many-to-many with links. Every link is a new call if you're using for example PowerBI. The result is that it takes a very long time to retrieve and is resource hungry. A better way is to publish the many-to-many through a RESTService. Thanks

### CODE REVIEW

**Comment by Adam-Dupaski** [comment]
@lightpeak please sign the [CLA](https://www.clahub.com/agreements/mendix/docs).

**Comment by lightpeak** [comment]
Signed the CLA!

**Comment by lightpeak** [comment]
> @lightpeak please sign the [CLA](https://www.clahub.com/agreements/mendix/docs).

Signed the CLA!

**Comment by Adam-Dupaski** [comment]
@joostverhoog please add comments/content when possible.

**Comment by Adam-Dupaski** [comment]
@lightpeak Thanks for the suggestion, but we have decided to not merge this for the following reasons:
- "Each link is a new call" is not accurate
- This document is about representation of OData, but your suggestion is about implementation
- We do not want to document for a specific user scenario in regards to a third-party tool like PowerBI
Cheers.

**Comment by RCatersels** [comment]
True but info on how to expose multiple multiple references to a BI tool is relevant and not only for Microsoft BI.

**Comment by Adam-Dupaski** [comment]
@RCatersels please see first point as main reason for not merging. We would push this info towards the Forum rather than documentation.

**Pull request closed without merging**
