### PR TITLE
Native SVG documentation

### PR DESCRIPTION
**Pull request by Robinfr**
Added documentation on native mobile SVGs.

### CODE REVIEW

**Comment by ConnorLand** [comment]
@Robinfr This doc looks good. The last thing to change is the placement. This doc is a Reference Guide, not a How To. 

Please drag and drop the markdown file in to this folder */refguide/native-mobile*. 

Also please delete the existing link to it in */howto/mobile/native-mobile* and add a link to it in */refguide/native-mobile*. 

After that we are good to go.

**Comment by Robinfr** [comment]
Added before/after images and moved it to refguide.

**Comment by ConnorLand** [comment]
> Added before/after images and moved it to refguide.

Did you commit your changes? I don't see the images or a commit.

**Comment by Robinfr** [comment]
Maybe.. not? Forgot to push will do it when I get home.

**Comment by Robinfr** [comment]
Pushed!

**Pull request merged**
