### PR TITLE
Update custom-settings.md

### PR DESCRIPTION
**Pull request by gnmarcos**
Changed persistentSessions default value from false to true - this changed for Mendix 7

### CODE REVIEW

**Comment by gnmarcos** [comment]
Hi Mark,

I would be happy to, but I can find what you're describing. I see a few details buttons, but can't find "Contributor has signed...". Can you say what I can do to get there please?

Thanks
Gonçalo

**Comment by JelteMX** [comment]
@gnmarcos The CLA can be found here: https://www.clahub.com/agreements/mendix/docs

At the bottom you will need to login with Github and the you can sign it.

**Comment by gnmarcos** [comment]
Done! Although I just realised I was logged in with my gmail account instead of my Mendix account (which I used to say "I agree". I hope that's ok.

**Comment by MarkvanMents** [comment]
Great. I'll release it - just looking at one more PR first.

**Pull request merged**
