### PR TITLE
SAP How-to's: Changes identified when following the instructions

### PR DESCRIPTION
**Pull request by MarkvanMents**

### CODE REVIEW

**Comment by Adam-Dupaski** [comment]
Looks good @MarkvanMents. Only needed to change "SAP Cloud platform" to "SAP Cloud Platform" based on SAP's style guide.

**Comment by Adam-Dupaski** [comment]
Hi @MarkvanMents. There was a broken link in this PR: "(howto/security/create-a-secure-app)" needed to be "(../security/create-a-secure-app)", because "security" is only a sub-folder in the same main folder as "Use the SAP XSUAA Connector." When sending a PR, please try to make sure there will be no merge conflicts by checking the **continuous-integration/travis-ci-pr** build log at the bottom (click **Details** to see the test results if necessary, and you can see any errors in the log). Thanks.

**Comment by MarkvanMents** [comment]
Sorry, Adam.
Is there a way to test this when I’m editing locally?
Is there some documentation on using travis-ci-pr, I can’t remember whether we covered it in our meetings?
Perhaps you can go through this at our meeting tomorrow as I have obviously missed something important?
Mark

**Comment by Adam-Dupaski** [comment]
No problem Mark, we’ll go over this tomorrow. Using Travis is relatively simple. Fixing build errors and merge conflicts takes some practice. 😊

**Pull request merged**
