### PR TITLE
add scope descriptions for mx:app:stories:read and mx:app:stories:write

### PR DESCRIPTION
**Pull request by disharth**

### CODE REVIEW

**Comment by disharth** [comment]
@Adam-Dupaski : Ronny would like to review/aware of these changes.

**Comment by Adam-Dupaski** [comment]
@disharth when should this be published?

**Comment by disharth** [comment]
> @disharth when should this be published?

Ronny's team(Identity Services) can tell about specific dates when are they releasing . I couldn't find a way to tag him here.

**Comment by Adam-Dupaski** [comment]
Should be published along with Stories API.

**Pull request merged**
