### PR TITLE
Added information about new .mpr format: MPRv2

### PR DESCRIPTION
**Pull request by tknippenberg**

### CODE REVIEW

**Comment by tknippenberg** [comment]
@PavelShirvanov and @robertvmx, can you do a quick review?

**Comment by MariaShaposhnikova** [comment]
@tknippenberg , I've reviewed the changes. Shall I merge the PR or is it for a future release?

**Comment by tknippenberg** [comment]
> @tknippenberg , I've reviewed the changes. Shall I merge the PR or is it for a future release?

Its not dependent on a specific release!

**Comment by PavelShirvanov** [comment]
> @PavelShirvanov and @robertvmx, can you do a quick review?

Looks good to me :+1:

**Review by PavelShirvanov — APPROVED** [review]

**Pull request merged**
