### PR TITLE
Update Preferences Dialog

### PR DESCRIPTION
**Pull request by NikolaMendix**
This will reflect changes from story 'Theme switch with Auto option (Release Dark mode)'

### CODE REVIEW

**Comment by ConnorLand** [comment]
This PR covers dark mode being moved into the Work Environment tab for GA, as well as includes details on its default mode (Auto, which has Studio Pro be light or dark depending on your OS).

**Review by ConnorLand — APPROVED** [review]

**Comment by ConnorLand** [comment]
LGTM for release day, anyone can merge this when it's time for GA.

**Review by ConnorLand — APPROVED** [review]

**Comment by Adam-Dupaski** [comment]
@ConnorLand are you doing a language review? Who is this assigned to?

**Comment by ConnorLand** [comment]
> @ConnorLand are you doing a language review? Who is this assigned to?

Thanks for the check Adam. I meant to self-assign. It is now assigned to me, and I've done a language review.

**Pull request merged**
