### PR TITLE
Removed iframe Modelshare

### PR DESCRIPTION
**Pull request by Criccle**
Iframes aren't supported in markdown:

http://stackoverflow.com/questions/14951321/how-to-display-html-content-in-github-readme-md

### CODE REVIEW

**Comment by JelteMX** [comment]
Iframes are normally not supported in Markdown, but HTML can be used in Markdown. So in that sense, iframes do work in Markdown. I changed the example in the contribution guideline, that one works. With the earlier example that you want to delete, it is missing a quote, which does not make it render

**Comment by JelteMX** [comment]
See [this change](https://github.com/mendix/docs/commit/3b4a487e9c957832440a79bf52ec0dec5fe836c9#diff-27a585c5d0ea1abf67cfd25578694743L75). I think we can close this PR, @jandevriesmendix

**Comment by Criccle** [comment]
Does not seem to work though.

image

**Comment by JelteMX** [comment]
True, not on Github. It does work on the website though

**Comment by JelteMX** [comment]
See the result [here](https://docs.mendix.com/community/documentation/content-writing-and-formatting-guidelines)

**Comment by Criccle** [comment]
Thanks Jelte! I was convinced it didn't work, my bad!

**Pull request closed without merging**
