### PR TITLE
Add avoiding exclusive access rules for the same user

### PR DESCRIPTION
**Pull request by dahfjkg**

### CODE REVIEW

**Comment by Adam-Dupaski** [comment]
@MarkvanMents seems like something for your interest and in context of best practices.

**Review by basdebakker — APPROVED** [review]
Looks good to me.

**Review by MarkvanMents — APPROVED** [review]
Hi Bas and Pavel (@basdebakker and @dahfjkg )
I've made this a bit more direct as I think this makes it clearer. Can you make sure I haven't mangled the meaning.
Let me know if it's still OK and I'll merge it.
Thanks for the PR.

**Comment by dahfjkg** [comment]
> Hi Bas and Pavel (@basdebakker and @dahfjkg ) I've made this a bit more direct as I think this makes it clearer. Can you make sure I haven't mangled the meaning. Let me know if it's still OK and I'll merge it. Thanks for the PR.

Looks clearer indeed, thanks for updating it. Let's merge.

**Pull request merged**
