### PR TITLE
Improve documentation on Mendix Studios target

### PR DESCRIPTION
**Pull request by MarkvanMents**
Updated to include information about Studio Pro.
See TW-1108.

### CODE REVIEW

**Comment by NielsTrots** [comment]
@MarkvanMents thanks for this. Can you also include the results of enabling this action? 
And in the release notes, please explain our end users what the idea is behind certain changes in the platform. For Developers it can make sense in their reality but for end users totally not. Especially when we change something that worked fine before and was accepted by the community as standard behavior. People need to understand why we do things.

**Comment by MarkvanMents** [comment]
Hi Neils,
I'm not sure what you mean by "the results of enabling this action".

I explain at the end:
> You have selected the target environment and can now deploy your app to that environment from either Studio or Studio Pro.

**Comment by MarkvanMents** [comment]
I also updated the release note this morning from a request from Feddo (https://github.com/mendix/docs/pull/2703)

Does this need any extra information or has Feddos text resolved your issue? The release note now explains that by selecting a target this is where your app will be deployed.

**Comment by feddovanede** [comment]
I think that the release notes now more clearly explain what the result of the change in the flow is: clicking the Deploy to Licensed Node now creates a deployment package _and_ automatically deploys it to the Target environment.

**Comment by RCatersels** [comment]
Now only the option to turn off automatic deployment or even disable this option all together. I still think that this "feature" has not been thought through. We want deployments under control and not by mistake because some new developer just pressed the wrong button in the modeler.

**Comment by MarkvanMents** [comment]
@RCatersels 
Hi Ronald,
Thanks for reaching out about this feature.
Unfortunately, as a technical writer I can only document the features which are released and explain them to customers.
I have forwarded your comments to the teams involved and will let you know if I get any feedback from them.
I realize that you would like to communicate the issues which this change is causing you. I think that the best channels would be via Mendix support and the Mendix forum.

**Comment by MarkvanMents** [comment]
@RCatersels 
Hi Ronald,
I see you have also discussed this in the forum: https://forum.mendix.com/link/questions/102390. I believe the development teams are working on improving the experience and preventing the issues you mention.
I think the best I can do here is clarify that the target doesn't have to be set and explain how to get your MDA into the Developer Portal.

**Comment by MarkvanMents** [comment]
@NielsTrots 
This document talks about using the **Run** command in Studio Pro.
Do you know whether the same applies to the **Deploy to Licenced Cloud Node** option?
image

**Comment by MarkvanMents** [comment]
@NielsTrots 
Hi Niels, is this now OK to publish?

**Comment by NielsTrots** [comment]
@MarkvanMents looks good, go for it. Thanks!

**Pull request merged**
