### PR TITLE
[SOLP-2592] Adding info about version control dump

### PR DESCRIPTION
**Pull request by blis-mendix**

### CODE REVIEW

**Comment by quinntracy** [comment]
Hi @blis-mendix , are these updates ready for review?

**Comment by blis-mendix** [comment]
Hey, yeah!

**Review by quinntracy — APPROVED** [review]

**Comment by blis-mendix** [comment]
Hey @quinntracy I will need to update this PR as if I'm correct freeze is today for 10.14 and weren't able to merge this patch in time so we will move it to the 10.15

**Comment by blis-mendix** [comment]
@quinntracy  I have updated the PR (change from 10.14 to 10.15

**Comment by quinntracy** [comment]
To be merged with 10.15 release

**Pull request merged**
