### PR TITLE
Remove info about swift storage

### PR DESCRIPTION
**Pull request by emirmx**
Swift storage is not supported after Mendix 7

### CODE REVIEW

**Comment by MarkvanMents** [comment]
Hi @emirmx 
Should I also be removing references to swift from:

- https://docs.mendix.com/developerportal/deploy/run-mendix-docker-image/#3-compatibility (section 3)
- https://docs.mendix.com/refguide/logging/#mendix-nodes (lognode StorageSwift)

And the Mx 8 versions of these document?

(I see that there was a release note in https://docs.mendix.com/releasenotes/studio-pro/8.0/#deprecations)

**Comment by emirmx** [comment]
> Hi @emirmx Should I also be removing references to swift from:
> 
>     * https://docs.mendix.com/developerportal/deploy/run-mendix-docker-image/#3-compatibility (section 3)
> 
>     * https://docs.mendix.com/refguide/logging/#mendix-nodes (lognode StorageSwift)
> 
> 
> And the Mx 8 versions of these document?
> 
> (I see that there was a release note in https://docs.mendix.com/releasenotes/studio-pro/8.0/#deprecations)

Yes, they can also be removed.

**Comment by MarkvanMents** [comment]
Removed additional references in https://github.com/mendix/docs/commit/27f3821ea173f29273c5f4bfaec597d456a0b9a5

**Review by MarkvanMents — APPROVED** [review]
Thanks for the PR
I removed other references to Swift too. https://github.com/mendix/docs/commit/27f3821ea173f29273c5f4bfaec597d456a0b9a5

**Pull request merged**
