### PR TITLE
Update release notes for CPLM005 release

### PR DESCRIPTION
**Pull request by ekremsekerci**
Added improvements & bug fixes that come along with the new CPLM release

### CODE REVIEW

**Comment by dbreseman** [comment]
@ekremsekerci, could you please give me write access so I can make a few minor language edits?

**Comment by ekremsekerci** [comment]
> @ekremsekerci, could you please give me write access so I can make a few minor language edits?

Just added you as a collaborator

**Comment by dbreseman** [comment]
Thanks!

**Comment by dbreseman** [comment]
@ekremsekerci Was the 2FA link added somewhere in the Metrics app?

**Pull request merged**
