### PR TITLE
Explain DefaultAzureCredential support

### PR DESCRIPTION
**Pull request by emirmx**
For Mx 10.10

### CODE REVIEW

**Review by MarkvanMents — APPROVED** [review]
Hi Emir
(@emirmx)
I've proofread this and approved it. Is it OK to publish immediately?
Thanks for the PR.
Mark

**Comment by emirmx** [comment]
> Hi Emir (@emirmx) I've proofread this and approved it. Is it OK to publish immediately? Thanks for the PR. Mark

The MR that implements it is just merged, so it will be available in 10.10. What will we do in such cases?

**Comment by MarkvanMents** [comment]
> > Hi Emir (@emirmx) I've proofread this and approved it. Is it OK to publish immediately? Thanks for the PR. Mark
> 
> The MR that implements it is just merged, so it will be available in 10.10. What will we do in such cases?

I'll put a label on it that it will be released in 10.10 and then it will be picked up and merged automatically on the day that 10.10 is published.

**Comment by emirmx** [comment]
> > > Hi Emir (@emirmx) I've proofread this and approved it. Is it OK to publish immediately? Thanks for the PR. Mark
> > 
> > 
> > The MR that implements it is just merged, so it will be available in 10.10. What will we do in such cases?
> 
> I'll put a label on it that it will be released in 10.10 and then it will be picked up and merged automatically on the day that 10.10 is published.

Thanks :-)

**Comment by emirmx** [comment]
I accidentally closed the MR instead of resolving the comment :-( 
But now re-opened.

**Pull request merged**
