### PR TITLE
Ats1.8 new bestpractice structure

### PR DESCRIPTION
**Pull request by zwartd**
Fixed all the links.

### CODE REVIEW

**Comment by jandevriesmendix** [comment]
Hi,
There are still some build errors. Please check them.

**Comment by zwartd** [comment]
Hi i checked the build error. It says that the images are not found. I changed the image links to make them more robust but it fails again. However the images and all the links are correct.

**Comment by zwartd** [comment]
Another idea is to remove the existing docs and replace them with exact copies.

**Comment by jandevriesmendix** [comment]
@JelteMX can you please check the build error? As far as I can see the links are correct. What is the problem?

**Comment by zwartd** [comment]
@jandevriesmendix I fixed it by removing all the old files and replacing them with the renamed files.

**Comment by jandevriesmendix** [comment]
Ok, I will review tomorrow.

**Pull request merged**
