### PR TITLE
New backup region and replication regions

### PR DESCRIPTION
**Pull request by aliozcan**
This PR introduces 2 new things:
- Replication region for all available regions
- New region (Canada)

### CODE REVIEW

**Comment by aliozcan** [comment]
@MarkvanMents @tomedegroot, can you guys have a look at this, please?

**Review by tomedegroot — COMMENTED** [review]
Great work @aliozcan

**Review by MarkvanMents — APPROVED** [review]

**Comment by MarkvanMents** [comment]
@aliozcan - I assume this can be merged immediately?

**Comment by MarkvanMents** [comment]
Merging immediately.

**Pull request merged**
