### PR TITLE
ATS 2.9 Release notes do not publish before 17 July

### PR DESCRIPTION
**Pull request by gajduk-mansystems**
**do not publish before 17 July**

### CODE REVIEW

**Comment by Adam-Dupaski** [comment]
@gajduk-mansystems The build is failing, please fix the error specified under *continuous-integration/travis-ci/pr*.

**Comment by Adam-Dupaski** [comment]
@gajduk Please fix the build error: https://travis-ci.org/mendix/docs/builds/402997524?utm_source=github_status&utm_medium=notification

**Comment by gajduk-mansystems** [comment]
@Adam-Dupaski  I removed the broken link.

**Comment by MariaShaposhnikova** [comment]
@gajduk-mansystems I have noticed that you had a link to this page (https://docs.mendix.com/howto40/Set+up+a+separate+Internet+Information+Services+server) in installation.md which doesn't exist. Can you please specify what document you referred to?

**Pull request merged**
