### PR TITLE
Add information about transaction isolation and deadlocks

### PR DESCRIPTION
**Pull request by jveldhuizen**

### CODE REVIEW

**Comment by Adam-Dupaski** [comment]
Need verification on mention of "since Mendix 6.10.6 and 7.2."

**Comment by jveldhuizen** [comment]
The latest public Mendix 6 version at this moment is 6.10.5.
The latest public Mendix 7 version at this moment is 7.0.2 and almost 7.1.

In 6.10.6 and each newer 6 version and in 7.2 and each newer 7 version, we will change the default transaction isolation level to Read Committed.
We cannot simply say ‘since Mendix 6.10.6’, because Mendix 7.0 and 7.1 still uses another transaction isolation level, because they are already (almost) released.

Van: Adam Dupaski [mailto:notifications@github.com]
Verzonden: donderdag 23 maart 2017 16:01
Aan: mendix/docs <docs@noreply.github.com>
CC: Jonathan Veldhuizen <Jonathan.Veldhuizen@mendix.com>; Author <author@noreply.github.com>
Onderwerp: Re: [mendix/docs] Add information about transaction isolation and deadlocks (#251)


Need verification on mention of "since Mendix 6.10.6 and 7.2."

**Comment by Adam-Dupaski** [comment]
Then I propose separating the version details by doc. It is not necessary to mention version 7 in a doc that is for version 6, and vice versa.

For the version 6 doc, I will write: "since version 6.10.6 (for Mendix 6)". For the version 7 doc, I will write: "since version 7.2.0 (for Mendix 7)".

These pull requests cannot be merged until 6.10.6 and 7.2.0 are released.

**Comment by Adam-Dupaski** [comment]
Ready to merge upon release of 6.10.6.

**Pull request merged**
