### PR TITLE
Remove RH->PBAR conversion doc (oct 2017)

### PR DESCRIPTION
**Pull request by knorrie**
Please merge after Oct 1st 2017. I don't expect anyone to need this page
any more at that point. Since the end of Aug 2017, this page was already
not linked to internally, but only from emails customers got about the
conversion.

### CODE REVIEW

**Comment by Adam-Dupaski** [comment]
Hans, please sign the [CLA](https://www.clahub.com/agreements/mendix/docs).

**Comment by Adam-Dupaski** [comment]
Remove links in other docs upon merge.

**Comment by Adam-Dupaski** [comment]
Via your comment in PR #670, this document is actually referenced in other docs. See the errors at the bottom of this build log: https://travis-ci.org/mendix/docs/builds/265557500?utm_source=github_status&utm_medium=notification

**Comment by knorrie** [comment]
Yeah, ok, it's not referenced in other documentation any more since merging #670 so I rebased this branch on top of that and repushed it. This doesn't alter the changes, but makes the test succeed.

**Comment by knorrie** [comment]
Why do I need to do the CLA step again? Did it lose info about me?

**Comment by knorrie** [comment]
Ah right, and that also doesn't apply because there has been some "gardening" done in the pages. Rebasing on current development branch instead now. ¯\_(ツ)_/¯

**Pull request merged**
