### PR TITLE
[NC-768] Gallery widget

### PR DESCRIPTION
**Pull request by UrazAkgultan**

### CODE REVIEW

**Comment by UrazAkgultan** [comment]
Don't merge pending tech check

**Comment by Adam-Dupaski** [comment]
@Luyao-Zhang-1 this can probably wait till @ConnorLand returns from PTO, so I'll remove you from Assignees

**Review by Ahmad-Elsayed — APPROVED** [review]

**Review by Ahmad-Elsayed — APPROVED** [review]

**Review by Ahmad-Elsayed — APPROVED** [review]

**Comment by UrazAkgultan** [comment]
Please don't merge. We will merge this PR when we release the Gallery widget

**Comment by Adam-Dupaski** [comment]
@ConnorLand please verify finalized content and publication upon return

**Review by ConnorLand — APPROVED** [review]

**Review by ConnorLand — APPROVED** [review]

**Comment by ConnorLand** [comment]
This will be merged with the new widget update, which will happen in the next day or so.

**Review by ConnorLand — APPROVED** [review]

**Pull request merged**
