### PR TITLE
WIP: Known issue in full screen mode for Mx9.0.5

### PR DESCRIPTION
**Pull request by MarkvanMents**
Draft text change - probably not needed and will be discarded after the release.

### CODE REVIEW

**Comment by rodrigocmoreira** [comment]
Hi Mark, looks good to me!

**Comment by Adam-Dupaski** [comment]
These notes should cross-reference the KI in the RN (once it is added). Version will probably be called 9.0 and not 9.0.5 (to be verified). See this PR for RN: #3146

**Comment by MarkvanMents** [comment]
> 
> 
> These notes should cross-reference the KI in the RN (once it is added). Version will probably be called 9.0 and not 9.0.5 (to be verified). See this PR for RN: #3146

@Adam-Dupaski So far all the release candidates are 9.0.5 - when are they planning to change the version number?
image

**Comment by Adam-Dupaski** [comment]
@MarkvanMents I don't know, but for the purposes of documentation, I've verified this will be 9.0.0. That's what will be in the RN as well.

**Comment by Adam-Dupaski** [comment]
@MarkvanMents I don't know that this doc update is necessary. We normally don't update docs with KI issues - we leave the KI in the RN with the expectation it will be resolved soon. This saves a dependency and another update. Note that this KI has not been added to the RN draft in GitLab yet. What do you think?

**Comment by Adam-Dupaski** [comment]
@rodrigocmoreira haven't seen this known issue added to the release notes draft in GitLab. Has this been verified to be a public known issue for the 9.0.5 release?

**Comment by MarkvanMents** [comment]
I think that it is a big enough issue in the GA version of the documentation that it should be documented. I don't think we can guarantee that the customer will look at the release notes in detail. This is the first version of the Mx9 documentation, so it will look odd to have something in there that doesn't work.
But I'll think about it.
I've taken up the versioning issue with you in Slack.

**Comment by Adam-Dupaski** [comment]
@MarkvanMents I think it's more likely they'll look at a Known Issue in the RN more than at this doc. Also, it becomes a problem with what versions to cite and what RN to link to. If this extends to 9.2, for example, you'd have a lot of small updates to do.

**Comment by MarkvanMents** [comment]
OK - I'll mark this draft so that we don't merge it while we discuss it.
@rodrigocmoreira would you be happy to leave this to be in the release notes only?

**Comment by Adam-Dupaski** [comment]
Still no KI in RN for this.

**Comment by Adam-Dupaski** [comment]
@MarkvanMents this has been added as a KI to 9.0.5 RN. Still don't think this addition to the text is necessary. Plan is to fix in 9.1.

**Comment by MarkvanMents** [comment]
I'll leave this as a draft until docs are published. If we get no feedback about needing it I'll close it a couple of days after GA.

**Comment by rodrigocmoreira** [comment]
Hi @MarkvanMents, I will send you a message if it's fixed for Mx9.1.0

**Comment by MarkvanMents** [comment]
This is on track to be fixed in 9.2.0.
I will remove this PR as it can easily be created again if there are continuing problems.
For now it will stay just as a KI in the release notes.

**Pull request closed without merging**
