### PR TITLE
Added known issues

### PR DESCRIPTION
**Pull request by JelleDekker**
Added a list of known issues based on current tickets, see tickets 52930, 52974 and 53027 for more details.

### CODE REVIEW

**Comment by Adam-Dupaski** [comment]
Hi Jelle,
We do not merge PRs on release notes, so I will close this. 
The process for known issues involves Mendix Support and R&D, so release notes can only be updated with known issues via those channels.
We are planning on improving the way known issues documented, so these specific known issues should appear in the documentation when the improvements are implemented.
Thanks,
Adam

**Comment by JelleDekker** [comment]
I have a big problem with this. In the past I could update the release notes via this channel, and if you say that known issues will appear in the documentation only when the improvement is implemented, this means that every implementation partner upgrading their projects has to find the same bugs again and again. This is a waist of time and source of irritation for both Mendix Support and implementation partners.

**Comment by RvdBergConclusion** [comment]
I follow Jelle in this regard, Having the known issues available on short notice is key for developers. Being up to date with your Mendix version is preferred and not having to browse forum to find potential deal breakers makes life great. "We are planning on improving the way known issues documented, " - sounds like its not nearly done. Why remove the old way of working before something else (potentially better) is implemented?

**Comment by RCatersels** [comment]
Yes, we need this. I just complimented Mendix in the last MVP session about this issue. We need this kind of info ASAP.

**Comment by Adam-Dupaski** [comment]
Thanks for your comments. It is clear this is an important topic for the documentation.

First of all, let me clarify my comment above. "When the improvements are implemented" applies to the documentation improvements that we are currently working on. That has nothing to do with the fixes for the known issues.

We will continue publishing known issues before they are fixed. But each new known issue needs to be determined by R&D/Support and progress through the appropriate channel to be documented. 

We are improving the documentation of known issues so that it is more complete and consistent. This improvement will most likely involve a new document that lists all the known issues as they are determined by R&D. This will be updated as the known issues are fixed.

Like the release notes, this known issues document will be maintained and updated internally by R&D. Therefore, pull requests like this documenting Support tickets will not be merged.

Hope this clears everything up! We will have this documentation improvement up and working as soon as possible.

Thanks,
Adam

**Comment by RCatersels** [comment]
Could this be solved that Support approves these changes first before they get pushed? Just that like other documentation also gets approved first before it is being published? 

Regards,

Ronald

**Comment by JelleDekker** [comment]
Hi Adam,

Thanks for clarifying, that's good to hear. But as I understand this is currently not implemented yet, and for one of the issues I'm describing I got the remark from Support that this was already a known issue. For the others I got the confirmation from Support that they could reproduce the problem.

I care a lot less about how the known issues are presented in comparison to when this is done. If the issue isn't completely clear yet: please publish what is known about it ASAP so developers won't have to download each new Mendix release to find bugs that are already known.

**Comment by Adam-Dupaski** [comment]
Thanks for your comments. I will take all of these into account in my discussions with R&D and Support so that we can get this new documentation improvement out soon.

**Comment by Adam-Dupaski** [comment]
Update: there is now a new [Known Issues](https://docs.mendix.com/releasenotes/desktop-modeler/known-issues) document for version 7+ known issues. The support tickets from this pull request will be added if/when they are determined to be known issues and they are assigned.

**Pull request closed without merging**
