### PR TITLE
Update native style properties for add on widgets

### PR DESCRIPTION
**Pull request by jobvs**
I added some new style properties for add on widgets, the updated widgets will be released to the appstore later today. Also fixed a few small typos.

### CODE REVIEW

**Comment by Adam-Dupaski** [comment]
Is this to be merged now or for 8.0.0. B2?

**Comment by Adam-Dupaski** [comment]
I guess for 8.0.0. B2, since you referenced the PR you closed. Please note it helps to put this info in the title of your PR or to comment it.

**Comment by jobvs** [comment]
Sorry for the delay, it's not for beta 2, I should have been more clear. This part of the doc is about add on widgets which we release through the app store. I just released the new version so this doc can already be updated as well.

**Comment by Adam-Dupaski** [comment]
Ok thanks for the clarification

**Pull request merged**
