### PR TITLE
6 August - Improved Scaling dialog

### PR DESCRIPTION
**Pull request by aniruddhagalgali-mendix**
Planned release 6 August
This PR should not be merged till the JIRA story MET-424 is done

### CODE REVIEW

**Comment by MariaShaposhnikova** [comment]
@aniruddhagalgali , can you please explain this phase to me: "The maximum value for **Memory per instance** is the lower of the total memory provided by your plan and 32 GB."? I do not understand what is meant by "the lower of the total memory". 
Thanks in advance.

**Comment by aniruddhagalgali-mendix** [comment]
@MariaShaposhnikova let me try to explain it with an example. 
If the total memory provided by your plan is 16 GB, then the maximum value that you can allocate for **Memory per instance** is 16 GB.  If the total memory provided by your plan is 32 GB, then the maximum value that you can allocate for **Memory per instance** is 32 GB. 
However, if the total memory provided by your plan is 64 GB, **still** the maximum value that you can allocate for **Memory per instance** will remain 32 GB.

**Comment by MariaShaposhnikova** [comment]
@aniruddhagalgali-mendix , I have rewritten the note and moved it to a different document, please take a look.

**Comment by aniruddhagalgali-mendix** [comment]
@MariaShaposhnikova Thanks. The new location makes more sense I guess. 
In the sentence `The maximum value for Memory per instance is the lower number shown in the Total Allocated Memory of your plan, but it cannot exceed 32 GB.` Do we want to keep the word `lower`?

**Comment by MariaShaposhnikova** [comment]
@aniruddhagalgali-mendix , I kept the word "lower", because there is a warning in the **Scaling Your Environment in Mendix Cloud v4** document that says: You cannot exceed the total memory provided by your plan. This is shown as the **lower** number in **Total Allocated Memory**.
 So I thought we refer to the same number here. Is it not correct when talking about **Maximum memory per instance**?

**Comment by MariaShaposhnikova** [comment]
Disccused in Slack, I've corrected the phase to "The maximum value for Memory per instance equals the Total Allocated Memory of your plan, but it cannot exceed 32 GB."

**Comment by MariaShaposhnikova** [comment]
@MarkvanMents , please take a look at this PR when you are back.

**Review by MarkvanMents — COMMENTED** [review]
Changes look fine to me.

**Comment by aniruddhagalgali-mendix** [comment]
@MarkvanMents that is correct!

**Comment by MarkvanMents** [comment]
Release successful

**Pull request merged**
