### PR TITLE
[RTI-604] Changes for Windows Service Console 4.7 release

### PR DESCRIPTION
**Pull request by atennapel**

### CODE REVIEW

**Comment by MarkvanMents** [comment]
Hi Albert (@atennapel )
Since this has yesterday's date on it, I assume it can be published immediately?

**Comment by atennapel** [comment]
We are waiting for the Marketplace team to add the new installer to Marketplace. We'll reply here again when this is done, hopefully today still.

**Comment by atennapel** [comment]
@MarkvanMents marketplace update is done, this can be published now.

**Review by MarkvanMents — APPROVED** [review]
Updated the release date to today.
Release approved over Slack

**Pull request merged**
