### PR TITLE
Update native-svg.md

### PR DESCRIPTION
**Pull request by wpenris**
Adding a line on how to make sure any newly uploaded svgs become visible in the Make it Native app - this was quite a hassle to figure out. Hope this helps.

Best regards,

Wouter Penris

### CODE REVIEW

**Comment by smarki** [comment]
@wpenris can you elaborate how these svgs are being added to your app

**Comment by ConnorLand** [comment]
SVGs and images in general are going to receive a wide documentation update in the near future. I will try to include these amendments to that update.

**Review by ConnorLand — APPROVED** [review]

**Comment by ConnorLand** [comment]
Our SVG and images documentation update is still on the horizon. I will add this info as a warning message directly to the docs. If we optimize the product and have no need for the warning in the future, I'll remove it in future SVG updates.

**Comment by ConnorLand** [comment]
Info added in this commit: https://github.com/mendix/docs/commit/6621833f25470750ffcba7e323366e9cd00e0b84 

I will close this PR.

**Pull request closed without merging**
