### PR TITLE
Updated System requirements and Deployment support pages

### PR DESCRIPTION
**Pull request by ernororive**
Hi, 

I have updated the support statements of our external deployment. Could you review the links which I have added. Not sure if I configured these correctly. 

Thx
Gr
Erno

### CODE REVIEW

**Comment by MarkvanMents** [comment]
Hi @ernororive 
I'm looking at this now.
In the meantime, can you sign the cla for me (makes it easier to see whether the PR is really failing, instead of just failing on the cla. Thanks
image

**Comment by MarkvanMents** [comment]
@ernororive: I also had the following question about azure-deploy.md

> We have had some feedback on the Azure deployment documentation: https://docs.mendix.com/developerportal/deploy/azure-deploy. 
> I asked in Slack (https://mendix.slack.com/archives/C38KZUL9G/p1574859195002900) and Clyde says that there isn’t currently a supported way of deploying to Azure.

Should we be putting a warning at the top of the azure-deploy.md file to warn people about this, or is this actually the way that users should be deploying and Clyde is wrong?

**Comment by MarkvanMents** [comment]
@ernororive 
I've finished proofreading this - do you want to check, or shall I publish immediately?
Have you had time to look at the Azure deployment instructions which Clyde says don't work?
I'll publish this later today if I don't hear from you.

**Comment by ernororive** [comment]
Hi mark,

I will write a statement for the documentation. I agree, we should make a remark on the documentation.

Gr
Erno

**Pull request merged**
