### PR TITLE
3dviewer api doc 

### PR DESCRIPTION
**Pull request by YapingLang**

### CODE REVIEW

**Comment by YapingLang** [comment]
hi sorry i didn't get to create a folder and add those 2 pic in the folder. as my local git push facing 403 errors. so I just used github web ui , simple uploaded my local files to myself branch. there's no way to add a folder in the web ui...

**Comment by Luyao-Zhang-1** [comment]
@Adam-Dupaski  Where would be the best location for this doc? For now, it is placed under 3D Viewer, next to 3D Viewer for Teamcenter. Another logic location could be under API Documentation. What do you think?

**Comment by Adam-Dupaski** [comment]
@Luyao-Zhang-1 I think it should stay under the main 3D Viewer doc, because it's not the full API. It's more of a use case, so consider titling it more specifically "3D Viewer API Use Case."

**Comment by YapingLang** [comment]
Maybe name the markdown as  “Use 3D Viewer API”?  The full api reference link is in this markdown.

**Comment by Adam-Dupaski** [comment]
@YapingLang yes that's a better idea - "Use the 3D Viewer API" - CC: @Luyao-Zhang-1

**Comment by Luyao-Zhang-1** [comment]
Thank you @Adam-Dupaski and @YapingLang both for the advice. I will change the title to “Use 3D Viewer API” and leave it under the main 3D Viewer doc.

**Comment by Luyao-Zhang-1** [comment]
I have been waiting for the version number. This PR has been open for a long time. 
I will publish the rest of the content first. When the version number becomes known, I will add the following small part to the doc:

### 3.2 Other Sample Code Snippets

Starting from version xxx{{% todo %}}[Add the version number when it is decided]{{% /todo %}}, 3D Viewer module includes some out-of-box API actions. The module allows you to manipulate model parts via `RotatePart`, `ScalePart`, `SetPartColor`, and `TranslatePart` API actions. You can find these actions in the **Viewer3D** > **USE_ME** > **API Actions** folder in the **App Explorer** in Studio Pro. You can directly use them to create your custom logic for manipulating models. Check out the code implementation of these javascript actions, along with the [3D Viewer API Reference](http://3dviewer-apidoc.s3-website.eu-central-1.amazonaws.com/index/v2.1/apidoc/3dviewer.html). This may give you some ideas about how you want to make use of the 3D Viewer API.

**Pull request merged**
