### PR TITLE
Release 1.10.1 with Mx7 support and bug fixes

### PR DESCRIPTION
**Pull request by TolenE**
I'm still testing the Mx7 compatibility, so please wait with putting in production until the release.

Can be tomorrow afternoon, can also be early next week.

### CODE REVIEW

**Comment by Adam-Dupaski** [comment]
Also, please clarify what should be linked in the release notes. The download is available in the App Store, correct? However, the release notes mention two packages available for download, whereas the App Store has only one download available. Please clarify for this set of release notes.

**Comment by Adam-Dupaski** [comment]
Regarding the link, I want to link these release notes to the Web App Store. But only the latest version is available for download there. The older versions are only available for download in the Modeler App Store. This will affect how the release notes are written.

**Comment by TolenE** [comment]
Hi Adam,

How can I see your changes?

As for the versions. Both are 1.10.1. The one mpk runs on Mx7, the other on Mx6.2. I will ask Andrej to place the Mx7 one as the current version in the AppStore and make the Mx6.2 version available under ‘older versions’.

Best regards,

Bart

**Comment by Adam-Dupaski** [comment]
Hi Bart, you can see my changes in the most recent commit here. As for the version naming, let's wait until the packages are in the App Store to see how they are named, and then we can update the release notes here.

**Pull request merged**
