### PR TITLE
Add used storage space to V4 database disk usage graph.

### PR DESCRIPTION
**Pull request by joshp123**
The second info panel mentions the used storage metric not being present before the metric was enabled.

This is what that scenario looks like:
image

### CODE REVIEW

**Review by MarkvanMents — COMMENTED** [review]
@joshp123 
Looks great. I'll add a Release Note when I merge it. 
How about:
* We have added used storage space to the Database Node Disk Usage graph in Mendix Cloud v4.

Let me know when I can publish.

**Review by MarkvanMents — APPROVED** [review]

**Comment by joshp123** [comment]
Thanks Mark, that sounds great. You can publish whenever, I will put the changes live immediately. Cheers!

**Comment by MarkvanMents** [comment]
@joshp123 
Hi Josh,
I got an email from GitHub yesterday about this (already merged) pull request, but it is not clear to me whether there is something that needs to be changed.
Can you let me know if there is anything that needs adding/changing in the documentation.
Thanks.

**Comment by joshp123** [comment]
Hi @MarkvanMents , I'm not sure why you got an email here. From my side, everything is fine here - nothing needs to be changed in the documentation. Thanks!

Josh

**Pull request merged**
