### PR TITLE
Update migrating-your-mendix-database.md

### PR DESCRIPTION
**Pull request by RVeenvliet**
Added documentation for using the GUI of SAP BTP Cockpit to migrate to SAP HANA

### CODE REVIEW

**Comment by katarzyna-koltun-mx** [comment]
@RVeenvliet Reviewed. Should I publish immediately, or wait for the go ahead?

**Review by katarzyna-koltun-mx — APPROVED** [review]

**Comment by RVeenvliet** [comment]
Hi,

You can publish it, thanks!

________________________________
Van: katarzyna-koltun-mx ***@***.***>
Verstuurd: woensdag, augustus 9, 2023 6:53:37 p.m.
Aan: mendix/docs ***@***.***>
CC: Roy Veenvliet ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [mendix/docs] Update migrating-your-mendix-database.md (PR #6383)


@RVeenvliet<https://github.com/RVeenvliet> Reviewed. Should I publish immediately, or wait for the go ahead?

**Comment by RVeenvliet** [comment]
Hi,

Yes you can publish it, thanks!
________________________________

**Comment by katarzyna-koltun-mx** [comment]
Done, should be published in about 20-30 minutes.

**Comment by katarzyna-koltun-mx** [comment]
@RVeenvliet Just to let you know, it might take a little longer due to an issue with the build engine. I'll keep an eye on it - if needed, I'll try again later or tomorrow morning.

**Comment by katarzyna-koltun-mx** [comment]
The update is now published.

**Pull request merged**
