### PR TITLE
New DB support policy

### PR DESCRIPTION
**Pull request by grootjans**
- Add support policy for database vendor releases, 
- Updated database versions

The policy needs to be reviewed by Koert. The new version list needs to be reviewed by Andrej

### CODE REVIEW

**Comment by Adam-Dupaski** [comment]
@MarkvanMents can you please pick this up for the required verification?

**Comment by MarkvanMents** [comment]
@grootjans 

Are you confirming the policy with Koert and asking Andrej for review?

**Comment by grootjans** [comment]
@MarkvanMents yes, working on the confirmation.

**Comment by MarkvanMents** [comment]
Great. I'll merge once we have the confirmation (unless it is important to get it out before).

**Comment by grootjans** [comment]
@MarkvanMents I got a question about the wording. I used 'endeavor', but perhaps 'aims' might be a better substitution given the audience. As George Orwell wrote 'Never use a long word where a short one will do'. What do you think?

**Comment by MarkvanMents** [comment]
@grootjans
Interesting question.
There is (to me and, luckily backed up here https://forum.wordreference.com/threads/endeavour-or-aim.1809938/) a subtle difference between aim and endeavor.
Aim - what we want to do
Endeavor - what we are trying very hard to do (but might not succeed)
In this case I think **aim** is better as _endeavor_ makes it seem like we are trying really hard but we might still fail. Unless, of course, these things really are very difficult and users have to be understanding if we are 3 years behind the latest version.
How about:

> Mendix tries to support the most recent and patched versions of database vendors. We aim to add support for new vendor versions 2 minor versions after the vendor has released it.

Question: is this 2 Mendix minor versions later (i.e. if a vendor releases a new version in May 2019 when Mendix is on 8.0, then we will put it in Mendix 8.2) or is it 2 vendor minor versions (i.e. they release 11.2 and we will put 11.2 in our product when they reach 11.4). I can read it both ways.

**Comment by grootjans** [comment]
@MarkvanMents fantastic answer, and great suggestion. I like it.

**Comment by grootjans** [comment]
@MarkvanMents about the versions:
This is 2 Mendix minor versions later. (i.e. if a vendor releases a new version in May 2019 when Mendix is on 8.0, then we will put it in Mendix 8.2)

**Comment by MarkvanMents** [comment]
@grootjans 

Any progress with reviews by Koert and @ako ?

**Comment by grootjans** [comment]
@MarkvanMents I got the go-ahead from Koert and @ako.

**Pull request merged**
