### PR TITLE
Added choropleth example to AnyChart documentation

### PR DESCRIPTION
**Pull request by Maismaus**
I noticed there was a scattergeo chart instead of a choropleth map under the examples. Since I was working on a choropleth map, I figured I could add my example to the documentation.

### CODE REVIEW

**Comment by Adam-Dupaski** [comment]
@Luyao-Zhang-1 please investigate whether this is an example replacement or a supplement to the current example.

**Comment by Luyao-Zhang-1** [comment]
@Adam-Dupaski Will do.

**Comment by Luyao-Zhang-1** [comment]
@Adam-Dupaski I checked it against https://plot.ly/javascript/, which is an external resource for chart types given in [Any Chart Cheat] Sheet(https://docs.mendix.com/refguide/charts-any-cheat-sheet.
The new image is a good example for Choropleth Map. The old image is a scattergeo chart, so it is good to replace it.

**Comment by Adam-Dupaski** [comment]
@Luyao-Zhang-1 thanks for investigating. But I'm curious why the scattergeo chart should be replaced?

**Comment by Maismaus** [comment]
Hi @Adam-Dupaski , it is a header for choropleth map but it shows a scattergeo chart, which is confusing. There are already examples of scattergeo charts given above and below the choropleth map

**Comment by Adam-Dupaski** [comment]
Thanks @Maismaus.

Please continue @Luyao-Zhang-1.

**Comment by Luyao-Zhang-1** [comment]
@Maismaus Thank you for your contribution. Is it also good to include colorscale in the code? Or it is not necessary?

**Comment by Maismaus** [comment]
Hi @Luyao-Zhang-1, I kept the example simple because the other examples on this page are also really basic. You could add additional lines of configuration, it might be useful. For reference, this is the configuration as I am using it at the moment. You can take anything you want and add it to the code if you want. 
[ {
  "type": "choropleth",
  "locationmode": "country names",
  "locations": ["Germany", "Austria"],
  "z": [100, 300],
  "name": "Energy consumption data",
  "colorscale": [[0,"#009999"], [1, "#000028"]],
  "colorbar": {
    "outlinewidth": 0,
    "thickness": 10,
    "x": 1
  },
  "hovertext": "Average energy consumption",
  "hoverlabel": {
    "bgcolor": "#000028"
  }
} ]

**Comment by Luyao-Zhang-1** [comment]
@Maismaus Thanks. let's keep it simple and basic to be consistent. I will merge this PR.

**Pull request merged**
