### PR TITLE
Clarify Beta state of BYO vs TS Git

### PR DESCRIPTION
**Pull request by grootjans**
Updated version control main document to clarify what part of Git is still in Beta

### CODE REVIEW

**Review by MarkvanMents — APPROVED** [review]
I think we can publish this now. I don't think it needs to wait for @MariaShaposhnikova to approve.
Thanks for the update, Robbert.

**Comment by Adam-Dupaski** [comment]
This at least needed a language review @MarkvanMents @Yiyun333

**Comment by Adam-Dupaski** [comment]
Sorry I see there was one @MarkvanMents @Yiyun333 - will make a few more changes, best practice is to link RN

**Comment by Adam-Dupaski** [comment]
Further proofreading: https://github.com/mendix/docs/commit/b682446350de53f7f33feaf30a736fcae6f61b71

**Comment by Adam-Dupaski** [comment]
@Yiyun333 please see above commit for proofreading best practices

**Pull request merged**
