### PR TITLE
Clarify microflow list arguments for grid buttons

### PR DESCRIPTION
**Pull request by r0b1n**
Clarify the behavior for ticket 155164.

### CODE REVIEW

**Review by Adam-Dupaski — APPROVED** [review]

**Comment by Adam-Dupaski** [comment]
@Yiyun333 this is an example PR for logic/microflows

**Comment by Yiyun333** [comment]
> 

Thanks! I wonder whether changing _single-selection_ to _single selction_ will create inconsistent style with _multi-selection_ in this paragraph?

**Comment by Adam-Dupaski** [comment]
@Yiyun333 good question but "multi" is a prefix and "single" is an adjective, so I see them functioning differently here

**Comment by Yiyun333** [comment]
> @Yiyun333 good question but "multi" is a prefix and "single" is an adjective, so I see them functioning differently here

I see! Thanks for the clarification.

**Pull request merged**
