### PR TITLE
Added documentation for new list operations

### PR DESCRIPTION
**Pull request by Robinfr**
I've added documentation for two new list operations:
- Filter by expression
- Find by expression

Since this is a new category of operations, I've also added a new section to explain their operations.

Part of OFF-515

### CODE REVIEW

**Comment by Robinfr** [comment]
@Adam-Dupaski I will undraft this when the MR is merged, which is currently in the testing phase if thats OK with you.

**Comment by Adam-Dupaski** [comment]
@Robinfr is this for 8.17?

**Comment by Robinfr** [comment]
No, for 9.0.3 probably

**Comment by Adam-Dupaski** [comment]
@Robinfr Oh yes I see the base now, thanks.

**Comment by Adam-Dupaski** [comment]
Change base after 9.0.2 release.

**Comment by Robinfr** [comment]
@Adam-Dupaski the MR has been merged to master so this can be reviewed since the feature will be released in the next version of Mx9.

**Review by Adam-Dupaski — APPROVED** [review]

**Pull request merged**
