### PR TITLE
Deploy API New Response

### PR DESCRIPTION
**Pull request by mustafa-karaoglu**
Added new error code to clean environment API.
Release delayed - possible 16 February. Awaiting confirmation.

### CODE REVIEW

**Review by MarkvanMents — APPROVED** [review]
Hi Mustafa,
Approving this.
Can it be published immediately, or does the new version of the API need to be release first?

**Comment by MarkvanMents** [comment]
Hi @mustafa-karaoglu - can you also sign the CLA agreement.
Not strictly necessary for Mendix employees, but it removes the warning and make it easier to manage the repo.
Thanks.
image

**Comment by mustafa-karaoglu** [comment]
Hi Mark,
We'll do our release on Thursday morning. If it can be published after that time, It would be better. Also, I signed CLA agreement.

**Comment by MarkvanMents** [comment]
Thanks Mustafa,
Please can you confirm on Thursday that the release was successful - then I'll publish.

**Comment by MarkvanMents** [comment]
Change released this morning. Publishing.

**Pull request merged**
