### PR TITLE
Update documentation for "Refresh in client" option (to be merged for 7.19)

### PR DESCRIPTION
**Pull request by ekrem-aktas**
We change behavior of "Refresh in client" option in several microflow actions and made the documentation of those actions a bit more explicit.

We also removed a hard-to-understand example from change object action. This example looked as coming out of nowhere without any introduction. Also, other actions do not have such examples. We remove it so be aligned with them. If you don't like it, please feel free to revert the last commit.

This PR should be merged with 7.18 release

### CODE REVIEW

**Comment by ekrem-aktas** [comment]
Hi Adam, we updated the documentation according to the latest code changes, also made it more explicit for nanoflows and also made it explicit that behavior changes with 7.18.0.

**Comment by Adam-Dupaski** [comment]
Thanks, I’ll take a look.

**Comment by ekrem-aktas** [comment]
Hi @Adam-Dupaski , important update, we want to merge this for 7.19, not 7.18. We'll update the versions mentioned in the documentations later

**Comment by ekrem-aktas** [comment]
@Adam-Dupaski, we updated the documentation again, would be happy if you can check it

**Comment by Adam-Dupaski** [comment]
@ekrem-aktas Reviewed and approved, thanks for the heads up.

**Pull request merged**
