### PR TITLE
restore backup locally

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by katamaks** [comment]
@jpulleman could you please help me out?

**Comment by katamaks** [comment]
@jtwaleson could you check again?

**Comment by Adam-Dupaski** [comment]
@jtwaleson Hey Jouke, what's the status of your review here? Can this be language-reviewed and published? Thanks.

**Comment by jtwaleson** [comment]
Still needs some improvements, I'll add it to my todo.

**Comment by Adam-Dupaski** [comment]
@jtwaleson Hi Jouke, do you think you can look at this in the next two weeks?

**Comment by MarkvanMents** [comment]
Pull request did two things:
New document and images "restore-backup-locally" - now moved to new branch ( MvM-RestoreBackupLocally-katamaks-patch-2 ) for review and testing
Additional borders around 20+ images - not needed as images were already OK - will discard these

Closing PR and working on new branch to text and proofread "restore backup locally"

**Pull request closed without merging**
