### PR TITLE
Update cloud-foundry-deploy.md

### PR DESCRIPTION
**Pull request by NikolaMendix**

### CODE REVIEW

**Comment by MarkvanMents** [comment]
@NikolaMendix 
Thanks for the PR - should it also have a deprecation notice added to this document: https://docs.mendix.com/refguide/run-menu/#2-menu-items-overview?

**Comment by NikolaMendix** [comment]
@MarkvanMents indeed, thanks. I forgot about that part. I have pushed commit for that. Here is how it currently looks in SP 
image

**Review by MarkvanMents — APPROVED** [review]
I've added the updated image.
OK to publish @NikolaMendix ?

**Comment by NikolaMendix** [comment]
> I've added the updated image. OK to publish @NikolaMendix ?

This deprecation is already in SP 10 so it is OK to publish. Thanks Mark!

**Pull request merged**
