### PR TITLE
[SOLP-2504] Menu item “Reverse Merge Changes ....” should be renamed with "Revert a commit ..."

### PR DESCRIPTION
**Pull request by PavelShirvanov**

### CODE REVIEW

**Comment by MariaShaposhnikova** [comment]
Hi @PavelShirvanov , thanks for the PR! Are these changes for a specific release or can they be merged once I do a language review?

**Comment by PavelShirvanov** [comment]
> Hi @PavelShirvanov , thanks for the PR! Are these changes for a specific release or can they be merged once I do a language review?

Seems we are ready to provide this renaming in 10.12

**Comment by PavelShirvanov** [comment]
The PR can be merge as it's ready to merge :)

**Review by MariaShaposhnikova — APPROVED** [review]

**Comment by MariaShaposhnikova** [comment]
@PavelShirvanov , I've missed your previous comment, sorry. Are changes already in production and not in 10.12?

**Comment by PavelShirvanov** [comment]
> @PavelShirvanov , I've missed your previous comment, sorry. Are changes already in production and not in 10.12?

It's in 10.12, the PR could be merge if there is no issue with the changes :)

**Pull request merged**
