### PR TITLE
Document web push notifications

### PR DESCRIPTION
**Pull request by gajduk-mansystems**
Added a how-to for using web push notifications. 
Describes the process of setting up, sending notifications and adding buttons to them

### CODE REVIEW

**Comment by ConnorLand** [comment]
Hello,

Thank you very much for submitting these documents. Your proposed documentation has some great implementation. 

Mendix is currently developing and evolving our push notification technology. As such, I plan on writing documentation on that topic in the future. So while I cannot merge this PR now (as our push notification implementation won't look exactly like yours) I would like to share your docs with our developers. We all plan on learning from this PR as we go forward and craft our own documentation in the future.

If you would like to post these docs on Mansystems' blog or another site, we encourage you to do so. Your solutions could help people in the interim before we publish our push notification updates.

Please let me know if you have any more questions or suggestions. 

Thank you for your PR,

Connor

**Comment by gajduk** [comment]
Dear @ConnorLand 

It makes me very sad to hear that you will not be publishing this PR.

I hereby declare that I do NOT consent with you copying my designs, code or documentation from this module. I worked very hard to write this module and accompanying documentation. Please take this into consideration.

Regards,
Andrej Gajduk

**Comment by old-profile** [comment]
Dear @ConnorLand

It makes me very sad to hear that you will not be publishing this PR. I hereby declare that I do NOT consent with you copying my designs, code or documentation from the module. I worked very hard to write this module and accompanying documentation.

Please take this into consideration.

Regards

**Comment by ConnorLand** [comment]
Hello,

I'm sorry this experience did not meet your expectations. I typically try and have all interactions with documentation exceed expectations. We will of course respect your wishes and not copy your designs, code, or documentation. 

To clarify this situation further, I can only publish docs which rely on platform-supported modules. I cannot publish docs which rely on community-supported modules.

However, your documentation can still reach people. You can publish your documentation as a community blog where I believe other Mendix users will greatly benefit from it: https://developers.mendix.com/community-blog/

In the future, please know that @Adam-Dupaski and myself are available for consultation before you undertake large documentation projects. If you reach out to one of us before writing new docs, we can help predict if there are any issues which would prevent publication. 

I am sorry you did not get to publish in the way you planned, and I appreciate the work that went into your submission. Please let me know if there's anything else we can do.

Connor

**Pull request closed without merging**
