### PR TITLE
Update Push Notifications Connector module dependencies

### PR DESCRIPTION
**Pull request by MxMurshed**
We are in the process of releasing a new version of the module v7.3.0. This should be published after the release.

We will communicate when the module is released.

### CODE REVIEW

**Comment by MxMurshed** [comment]
We have just released the module version 7.3.0 [here](https://marketplace.mendix.com/link/component/3003)

**Comment by MariaShaposhnikova** [comment]
@ConnorLand , can this PR be merged?

**Comment by ConnorLand** [comment]
There are conflicts, and this PR needs to target Mx9 docs as well.

I will enact this PRs changes in both Mx9 and Mx10 docs manually, post the commit here, and then close the PR.

**Review by ConnorLand — APPROVED** [review]

**Comment by ConnorLand** [comment]
The conflict was easy to fix so I just duplicated all the changes into Mx9 within this PR. Thanks @MendixMurshed !

**Pull request merged**
